// AUTO-GENERATED by `pnpm db:types` — do not edit by hand.
// Source: supabase gen types typescript --project-id yxenvzcfypfqzbpfyuiz --schema waytara
// Regenerate after schema migrations: SUPABASE_PROJECT_ID=yxenvzcfypfqzbpfyuiz pnpm db:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  waytara: {
    Tables: {
      alerts: {
        Row: {
          acknowledged_at: string | null
          acknowledged_by: string | null
          device_id: string
          id: string
          message: string
          severity: string
          ts: string
        }
        Insert: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          device_id: string
          id?: string
          message: string
          severity?: string
          ts?: string
        }
        Update: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          device_id?: string
          id?: string
          message?: string
          severity?: string
          ts?: string
        }
        Relationships: [
          {
            foreignKeyName: "alerts_acknowledged_by_fkey"
            columns: ["acknowledged_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "alerts_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          actor_role: Database["waytara"]["Enums"]["user_role"] | null
          changes: Json | null
          created_at: string
          entity: string
          entity_id: string | null
          id: number
        }
        Insert: {
          action: string
          actor_id?: string | null
          actor_role?: Database["waytara"]["Enums"]["user_role"] | null
          changes?: Json | null
          created_at?: string
          entity: string
          entity_id?: string | null
          id?: never
        }
        Update: {
          action?: string
          actor_id?: string | null
          actor_role?: Database["waytara"]["Enums"]["user_role"] | null
          changes?: Json | null
          created_at?: string
          entity?: string
          entity_id?: string | null
          id?: never
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      charging_sessions: {
        Row: {
          created_at: string
          device_id: string
          end_energy_kwh: number | null
          ended_at: string | null
          id: string
          is_test: boolean
          start_energy_kwh: number | null
          started_at: string
          stop_reason: string | null
        }
        Insert: {
          created_at?: string
          device_id: string
          end_energy_kwh?: number | null
          ended_at?: string | null
          id?: string
          is_test?: boolean
          start_energy_kwh?: number | null
          started_at: string
          stop_reason?: string | null
        }
        Update: {
          created_at?: string
          device_id?: string
          end_energy_kwh?: number | null
          ended_at?: string | null
          id?: string
          is_test?: boolean
          start_energy_kwh?: number | null
          started_at?: string
          stop_reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "charging_sessions_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_onboarding: {
        Row: {
          balance_payment_status: string
          created_at: string
          current_stage: Database["waytara"]["Enums"]["onboarding_stage"]
          customer_id: string | null
          employee_id: string | null
          id: string
          install_scheduled_at: string | null
          install_time_slot: string | null
          invite_status: Database["waytara"]["Enums"]["invite_status"] | null
          invite_token: string | null
          lead_id: string
          quotation_id: string | null
          updated_at: string
        }
        Insert: {
          balance_payment_status?: string
          created_at?: string
          current_stage?: Database["waytara"]["Enums"]["onboarding_stage"]
          customer_id?: string | null
          employee_id?: string | null
          id?: string
          install_scheduled_at?: string | null
          install_time_slot?: string | null
          invite_status?: Database["waytara"]["Enums"]["invite_status"] | null
          invite_token?: string | null
          lead_id: string
          quotation_id?: string | null
          updated_at?: string
        }
        Update: {
          balance_payment_status?: string
          created_at?: string
          current_stage?: Database["waytara"]["Enums"]["onboarding_stage"]
          customer_id?: string | null
          employee_id?: string | null
          id?: string
          install_scheduled_at?: string | null
          install_time_slot?: string | null
          invite_status?: Database["waytara"]["Enums"]["invite_status"] | null
          invite_token?: string | null
          lead_id?: string
          quotation_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_onboarding_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_onboarding_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_onboarding_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_onboarding_quotation_id_fkey"
            columns: ["quotation_id"]
            isOneToOne: false
            referencedRelation: "quotations"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          address: Json | null
          billing_email: string | null
          created_at: string
          id: string
          plan_id: string | null
          plan_started_at: string | null
          status: string
          tariff_rate_per_kwh: number
        }
        Insert: {
          address?: Json | null
          billing_email?: string | null
          created_at?: string
          id: string
          plan_id?: string | null
          plan_started_at?: string | null
          status?: string
          tariff_rate_per_kwh?: number
        }
        Update: {
          address?: Json | null
          billing_email?: string | null
          created_at?: string
          id?: string
          plan_id?: string | null
          plan_started_at?: string | null
          status?: string
          tariff_rate_per_kwh?: number
        }
        Relationships: [
          {
            foreignKeyName: "customers_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customers_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      device_parameters: {
        Row: {
          category: string | null
          device_type_id: string
          id: string
          is_required: boolean
          modbus_register: Json | null
          parameter_key: string
          parameter_name: string
          unit: string | null
        }
        Insert: {
          category?: string | null
          device_type_id: string
          id?: string
          is_required?: boolean
          modbus_register?: Json | null
          parameter_key: string
          parameter_name: string
          unit?: string | null
        }
        Update: {
          category?: string | null
          device_type_id?: string
          id?: string
          is_required?: boolean
          modbus_register?: Json | null
          parameter_key?: string
          parameter_name?: string
          unit?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "device_type_instruments_device_type_id_fkey"
            columns: ["device_type_id"]
            isOneToOne: false
            referencedRelation: "stock"
            referencedColumns: ["id"]
          },
        ]
      }
      device_readings: {
        Row: {
          created_at: string
          device_id: string
          id: number
          instrument_key: string
          is_test: boolean
          ts: string
          unit: string | null
          value: number | null
        }
        Insert: {
          created_at?: string
          device_id: string
          id?: never
          instrument_key: string
          is_test?: boolean
          ts: string
          unit?: string | null
          value?: number | null
        }
        Update: {
          created_at?: string
          device_id?: string
          id?: never
          instrument_key?: string
          is_test?: boolean
          ts?: string
          unit?: string | null
          value?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "device_readings_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
        ]
      }
      device_settings: {
        Row: {
          device_id: string
          id: number
          modbus_register: Json | null
          notes: string | null
          setting_category: string
          setting_key: string
          setting_value: string
          source: string | null
          ts: string
          unit: string | null
          written_by: string | null
        }
        Insert: {
          device_id: string
          id?: never
          modbus_register?: Json | null
          notes?: string | null
          setting_category: string
          setting_key: string
          setting_value: string
          source?: string | null
          ts?: string
          unit?: string | null
          written_by?: string | null
        }
        Update: {
          device_id?: string
          id?: never
          modbus_register?: Json | null
          notes?: string | null
          setting_category?: string
          setting_key?: string
          setting_value?: string
          source?: string | null
          ts?: string
          unit?: string | null
          written_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "device_settings_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "device_settings_written_by_fkey"
            columns: ["written_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      devices: {
        Row: {
          created_at: string
          device_status: Database["waytara"]["Enums"]["device_status"]
          id: string
          installation_id: string | null
          installed_at: string | null
          label: string | null
          service_id: string | null
          site_id: string
          stock_device_id: string
          updated_at: string
          warranty_end_date: string | null
          warranty_start_date: string | null
        }
        Insert: {
          created_at?: string
          device_status?: Database["waytara"]["Enums"]["device_status"]
          id?: string
          installation_id?: string | null
          installed_at?: string | null
          label?: string | null
          service_id?: string | null
          site_id: string
          stock_device_id: string
          updated_at?: string
          warranty_end_date?: string | null
          warranty_start_date?: string | null
        }
        Update: {
          created_at?: string
          device_status?: Database["waytara"]["Enums"]["device_status"]
          id?: string
          installation_id?: string | null
          installed_at?: string | null
          label?: string | null
          service_id?: string | null
          site_id?: string
          stock_device_id?: string
          updated_at?: string
          warranty_end_date?: string | null
          warranty_start_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "devices_device_type_id_fkey"
            columns: ["stock_device_id"]
            isOneToOne: false
            referencedRelation: "stock"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "devices_installation_id_fkey"
            columns: ["installation_id"]
            isOneToOne: false
            referencedRelation: "installations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "devices_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "service_contracts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "devices_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      employee_invites: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string | null
          role: Database["waytara"]["Enums"]["user_role"]
          status: Database["waytara"]["Enums"]["invite_status"]
          token: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at: string
          id?: string
          invited_by?: string | null
          role?: Database["waytara"]["Enums"]["user_role"]
          status?: Database["waytara"]["Enums"]["invite_status"]
          token: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          role?: Database["waytara"]["Enums"]["user_role"]
          status?: Database["waytara"]["Enums"]["invite_status"]
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "employee_invites_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      equipment_checks: {
        Row: {
          availability: boolean
          checked_by: string | null
          device_id: string
          id: string
          power_connect: boolean
          quality: boolean
          updated_at: string
        }
        Insert: {
          availability?: boolean
          checked_by?: string | null
          device_id: string
          id?: string
          power_connect?: boolean
          quality?: boolean
          updated_at?: string
        }
        Update: {
          availability?: boolean
          checked_by?: string | null
          device_id?: string
          id?: string
          power_connect?: boolean
          quality?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "equipment_checks_checked_by_fkey"
            columns: ["checked_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "equipment_checks_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: true
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
        ]
      }
      installations: {
        Row: {
          completed_at: string | null
          employee_id: string | null
          id: string
          notes: string | null
          scheduled_date: string | null
          site_id: string
          status: string
        }
        Insert: {
          completed_at?: string | null
          employee_id?: string | null
          id?: string
          notes?: string | null
          scheduled_date?: string | null
          site_id: string
          status?: string
        }
        Update: {
          completed_at?: string | null
          employee_id?: string | null
          id?: string
          notes?: string | null
          scheduled_date?: string | null
          site_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "installations_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "installations_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          accepted_at: string | null
          address: Json | null
          assigned_to: string | null
          created_at: string
          email: string
          full_name: string
          id: string
          message: string | null
          phone: string | null
          source: string | null
          status: Database["waytara"]["Enums"]["lead_status"]
          updated_at: string
        }
        Insert: {
          accepted_at?: string | null
          address?: Json | null
          assigned_to?: string | null
          created_at?: string
          email: string
          full_name: string
          id?: string
          message?: string | null
          phone?: string | null
          source?: string | null
          status?: Database["waytara"]["Enums"]["lead_status"]
          updated_at?: string
        }
        Update: {
          accepted_at?: string | null
          address?: Json | null
          assigned_to?: string | null
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          message?: string | null
          phone?: string | null
          source?: string | null
          status?: Database["waytara"]["Enums"]["lead_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "leads_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      maintenance_tickets: {
        Row: {
          charge_amount: number | null
          completed_at: string | null
          created_at: string
          customer_id: string
          description: string | null
          device_id: string | null
          employee_id: string | null
          id: string
          is_chargeable: boolean | null
          scheduled_date: string | null
          service_contract_id: string | null
          site_id: string
          status: string
          type: string
        }
        Insert: {
          charge_amount?: number | null
          completed_at?: string | null
          created_at?: string
          customer_id: string
          description?: string | null
          device_id?: string | null
          employee_id?: string | null
          id?: string
          is_chargeable?: boolean | null
          scheduled_date?: string | null
          service_contract_id?: string | null
          site_id: string
          status?: string
          type?: string
        }
        Update: {
          charge_amount?: number | null
          completed_at?: string | null
          created_at?: string
          customer_id?: string
          description?: string | null
          device_id?: string | null
          employee_id?: string | null
          id?: string
          is_chargeable?: boolean | null
          scheduled_date?: string | null
          service_contract_id?: string | null
          site_id?: string
          status?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "maintenance_tickets_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "maintenance_tickets_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "maintenance_tickets_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "maintenance_tickets_service_contract_id_fkey"
            columns: ["service_contract_id"]
            isOneToOne: false
            referencedRelation: "service_contracts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "maintenance_tickets_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount: number
          created_at: string
          customer_id: string | null
          gateway: string | null
          gateway_ref: string | null
          id: string
          method: string | null
          paid_at: string | null
          payment_type: Database["waytara"]["Enums"]["payment_type"]
          quotation_id: string
          status: Database["waytara"]["Enums"]["payment_status"]
        }
        Insert: {
          amount: number
          created_at?: string
          customer_id?: string | null
          gateway?: string | null
          gateway_ref?: string | null
          id?: string
          method?: string | null
          paid_at?: string | null
          payment_type: Database["waytara"]["Enums"]["payment_type"]
          quotation_id: string
          status?: Database["waytara"]["Enums"]["payment_status"]
        }
        Update: {
          amount?: number
          created_at?: string
          customer_id?: string | null
          gateway?: string | null
          gateway_ref?: string | null
          id?: string
          method?: string | null
          paid_at?: string | null
          payment_type?: Database["waytara"]["Enums"]["payment_type"]
          quotation_id?: string
          status?: Database["waytara"]["Enums"]["payment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "payments_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_quotation_id_fkey"
            columns: ["quotation_id"]
            isOneToOne: false
            referencedRelation: "quotations"
            referencedColumns: ["id"]
          },
        ]
      }
      plans: {
        Row: {
          code: Database["waytara"]["Enums"]["plan_code"]
          created_at: string
          features: Json
          id: string
          is_active: boolean
          max_devices: number | null
          name: string
          price_monthly: number
          price_yearly: number | null
        }
        Insert: {
          code: Database["waytara"]["Enums"]["plan_code"]
          created_at?: string
          features?: Json
          id?: string
          is_active?: boolean
          max_devices?: number | null
          name: string
          price_monthly: number
          price_yearly?: number | null
        }
        Update: {
          code?: Database["waytara"]["Enums"]["plan_code"]
          created_at?: string
          features?: Json
          id?: string
          is_active?: boolean
          max_devices?: number | null
          name?: string
          price_monthly?: number
          price_yearly?: number | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          deactivated_at: string | null
          deleted_at: string | null
          email: string
          full_name: string | null
          id: string
          notification_preferences: Json
          phone: string | null
          role: Database["waytara"]["Enums"]["user_role"]
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          deactivated_at?: string | null
          deleted_at?: string | null
          email: string
          full_name?: string | null
          id: string
          notification_preferences?: Json
          phone?: string | null
          role?: Database["waytara"]["Enums"]["user_role"]
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          deactivated_at?: string | null
          deleted_at?: string | null
          email?: string
          full_name?: string | null
          id?: string
          notification_preferences?: Json
          phone?: string | null
          role?: Database["waytara"]["Enums"]["user_role"]
        }
        Relationships: []
      }
      quotations: {
        Row: {
          accepted_at: string | null
          access_token: string
          advance_amount: number | null
          balance_amount: number | null
          created_at: string
          currency: string
          customer_message: string | null
          employee_id: string | null
          gst_amount: number | null
          gst_rate: number
          id: string
          lead_id: string
          payment_option: Database["waytara"]["Enums"]["payment_option"] | null
          pdf_url: string | null
          plan_id: string
          pricing_breakdown: Json
          rejected_at: string | null
          sent_at: string | null
          status: Database["waytara"]["Enums"]["quotation_status"]
          subtotal_amount: number | null
          total_amount: number
          valid_until: string | null
        }
        Insert: {
          accepted_at?: string | null
          access_token?: string
          advance_amount?: number | null
          balance_amount?: number | null
          created_at?: string
          currency?: string
          customer_message?: string | null
          employee_id?: string | null
          gst_amount?: number | null
          gst_rate?: number
          id?: string
          lead_id: string
          payment_option?: Database["waytara"]["Enums"]["payment_option"] | null
          pdf_url?: string | null
          plan_id: string
          pricing_breakdown?: Json
          rejected_at?: string | null
          sent_at?: string | null
          status?: Database["waytara"]["Enums"]["quotation_status"]
          subtotal_amount?: number | null
          total_amount: number
          valid_until?: string | null
        }
        Update: {
          accepted_at?: string | null
          access_token?: string
          advance_amount?: number | null
          balance_amount?: number | null
          created_at?: string
          currency?: string
          customer_message?: string | null
          employee_id?: string | null
          gst_amount?: number | null
          gst_rate?: number
          id?: string
          lead_id?: string
          payment_option?: Database["waytara"]["Enums"]["payment_option"] | null
          pdf_url?: string | null
          plan_id?: string
          pricing_breakdown?: Json
          rejected_at?: string | null
          sent_at?: string | null
          status?: Database["waytara"]["Enums"]["quotation_status"]
          subtotal_amount?: number | null
          total_amount?: number
          valid_until?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quotations_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotations_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotations_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      service_contracts: {
        Row: {
          created_at: string
          device_id: string
          end_date: string
          id: string
          service_plan_id: string | null
          start_date: string
        }
        Insert: {
          created_at?: string
          device_id: string
          end_date: string
          id?: string
          service_plan_id?: string | null
          start_date: string
        }
        Update: {
          created_at?: string
          device_id?: string
          end_date?: string
          id?: string
          service_plan_id?: string | null
          start_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_contracts_device_id_fkey"
            columns: ["device_id"]
            isOneToOne: false
            referencedRelation: "devices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_contracts_service_plan_id_fkey"
            columns: ["service_plan_id"]
            isOneToOne: false
            referencedRelation: "service_plans"
            referencedColumns: ["id"]
          },
        ]
      }
      service_plans: {
        Row: {
          covered_items: Json | null
          created_at: string
          device_category: string
          duration_months: number
          free_services_count: number
          id: string
          name: string
          paid_extras: Json | null
          per_extra_service_price_amount: number | null
          price_amount: number | null
          total_services_included: number
        }
        Insert: {
          covered_items?: Json | null
          created_at?: string
          device_category: string
          duration_months: number
          free_services_count?: number
          id?: string
          name: string
          paid_extras?: Json | null
          per_extra_service_price_amount?: number | null
          price_amount?: number | null
          total_services_included: number
        }
        Update: {
          covered_items?: Json | null
          created_at?: string
          device_category?: string
          duration_months?: number
          free_services_count?: number
          id?: string
          name?: string
          paid_extras?: Json | null
          per_extra_service_price_amount?: number | null
          price_amount?: number | null
          total_services_included?: number
        }
        Relationships: []
      }
      sites: {
        Row: {
          address: Json | null
          created_at: string
          customer_id: string
          id: string
          latitude: number | null
          longitude: number | null
          name: string
          power_package: Database["waytara"]["Enums"]["power_package"] | null
          power_source_category: Database["waytara"]["Enums"]["power_source_category"]
          property_type: Database["waytara"]["Enums"]["property_type"]
        }
        Insert: {
          address?: Json | null
          created_at?: string
          customer_id: string
          id?: string
          latitude?: number | null
          longitude?: number | null
          name: string
          power_package?: Database["waytara"]["Enums"]["power_package"] | null
          power_source_category: Database["waytara"]["Enums"]["power_source_category"]
          property_type: Database["waytara"]["Enums"]["property_type"]
        }
        Update: {
          address?: Json | null
          created_at?: string
          customer_id?: string
          id?: string
          latitude?: number | null
          longitude?: number | null
          name?: string
          power_package?: Database["waytara"]["Enums"]["power_package"] | null
          power_source_category?: Database["waytara"]["Enums"]["power_source_category"]
          property_type?: Database["waytara"]["Enums"]["property_type"]
        }
        Relationships: [
          {
            foreignKeyName: "sites_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      stock: {
        Row: {
          brand: string | null
          category: string
          created_at: string
          id: string
          manufacturer: string | null
          model: string | null
          model_number: string | null
          name: string
          pack_size: number | null
          po_reference: string | null
          power_capacity_unit: string | null
          power_capacity_value: number | null
          primary_uom: string | null
          purchase_date: string | null
          purchase_price_amount: number | null
          quantity: number
          serial_number: string | null
          size_unit: string | null
          size_value: number | null
          status: Database["waytara"]["Enums"]["stock_status"]
          supplier: string | null
          technical_specs: Json | null
          unit_price: number | null
          warranty_info: Json | null
        }
        Insert: {
          brand?: string | null
          category: string
          created_at?: string
          id?: string
          manufacturer?: string | null
          model?: string | null
          model_number?: string | null
          name: string
          pack_size?: number | null
          po_reference?: string | null
          power_capacity_unit?: string | null
          power_capacity_value?: number | null
          primary_uom?: string | null
          purchase_date?: string | null
          purchase_price_amount?: number | null
          quantity?: number
          serial_number?: string | null
          size_unit?: string | null
          size_value?: number | null
          status?: Database["waytara"]["Enums"]["stock_status"]
          supplier?: string | null
          technical_specs?: Json | null
          unit_price?: number | null
          warranty_info?: Json | null
        }
        Update: {
          brand?: string | null
          category?: string
          created_at?: string
          id?: string
          manufacturer?: string | null
          model?: string | null
          model_number?: string | null
          name?: string
          pack_size?: number | null
          po_reference?: string | null
          power_capacity_unit?: string | null
          power_capacity_value?: number | null
          primary_uom?: string | null
          purchase_date?: string | null
          purchase_price_amount?: number | null
          quantity?: number
          serial_number?: string | null
          size_unit?: string | null
          size_value?: number | null
          status?: Database["waytara"]["Enums"]["stock_status"]
          supplier?: string | null
          technical_specs?: Json | null
          unit_price?: number | null
          warranty_info?: Json | null
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          customer_id: string
          id: string
          payment_gateway_ref: string | null
          plan_id: string
          status: Database["waytara"]["Enums"]["subscription_status"]
        }
        Insert: {
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          customer_id: string
          id?: string
          payment_gateway_ref?: string | null
          plan_id: string
          status?: Database["waytara"]["Enums"]["subscription_status"]
        }
        Update: {
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          customer_id?: string
          id?: string
          payment_gateway_ref?: string | null
          plan_id?: string
          status?: Database["waytara"]["Enums"]["subscription_status"]
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      support_messages: {
        Row: {
          attachment_path: string | null
          body: string
          created_at: string
          id: string
          sender_id: string | null
          sender_role: string
          ticket_id: string
        }
        Insert: {
          attachment_path?: string | null
          body: string
          created_at?: string
          id?: string
          sender_id?: string | null
          sender_role: string
          ticket_id: string
        }
        Update: {
          attachment_path?: string | null
          body?: string
          created_at?: string
          id?: string
          sender_id?: string | null
          sender_role?: string
          ticket_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_messages_ticket_id_fkey"
            columns: ["ticket_id"]
            isOneToOne: false
            referencedRelation: "support_tickets"
            referencedColumns: ["id"]
          },
        ]
      }
      support_tickets: {
        Row: {
          created_at: string
          customer_id: string
          id: string
          status: string
          subject: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_id: string
          id?: string
          status?: string
          subject: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_id?: string
          id?: string
          status?: string
          subject?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_tickets_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      test_sessions: {
        Row: {
          data_purged: boolean
          employee_id: string | null
          ended_at: string | null
          id: string
          notes: string | null
          site_id: string
          started_at: string
          status: Database["waytara"]["Enums"]["test_session_status"]
        }
        Insert: {
          data_purged?: boolean
          employee_id?: string | null
          ended_at?: string | null
          id?: string
          notes?: string | null
          site_id: string
          started_at?: string
          status?: Database["waytara"]["Enums"]["test_session_status"]
        }
        Update: {
          data_purged?: boolean
          employee_id?: string | null
          ended_at?: string | null
          id?: string
          notes?: string | null
          site_id?: string
          started_at?: string
          status?: Database["waytara"]["Enums"]["test_session_status"]
        }
        Relationships: [
          {
            foreignKeyName: "test_sessions_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_sessions_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
      is_staff: { Args: never; Returns: boolean }
      update_device_site: {
        Args: {
          p_address: Json
          p_device_id: string
          p_latitude?: number
          p_longitude?: number
          p_name: string
          p_power_package?: Database["waytara"]["Enums"]["power_package"]
          p_power_source_category: Database["waytara"]["Enums"]["power_source_category"]
          p_property_type: Database["waytara"]["Enums"]["property_type"]
        }
        Returns: string
      }
    }
    Enums: {
      device_status: "test" | "active" | "offline" | "decommissioned"
      invite_status: "pending" | "accepted" | "expired" | "revoked"
      lead_status: "new" | "assigned" | "quoted" | "converted" | "lost"
      onboarding_stage:
        | "quotation_sent"
        | "quotation_accepted"
        | "payment_pending"
        | "account_created"
        | "site_setup"
        | "connection_test"
        | "install_scheduled"
        | "install_completed"
      payment_option: "full" | "split"
      payment_status: "pending" | "paid" | "failed" | "refunded"
      payment_type: "full" | "advance" | "balance"
      plan_code: "basic" | "pro" | "advance"
      power_package:
        | "solar_inverter"
        | "solar_battery_inverter"
        | "inverter_battery"
        | "solar_inverter_ev"
        | "solar_battery_inverter_ev"
        | "inverter_battery_ev"
        | "ev_charger_only"
      power_source_category: "grid_tied" | "off_grid" | "hybrid"
      property_type:
        | "residential_independent_villas"
        | "gated_communities_rwas_high_rises"
        | "factories_heavy_engineering_processing_plants"
        | "corporate_offices_hospitals_hotels_retail"
        | "logistics_delivery_hubs_bus_depots"
        | "tech_parks_data_centers_rnd_hubs"
      quotation_status:
        | "draft"
        | "sent"
        | "accepted"
        | "rejected"
        | "expired"
        | "revision_requested"
      stock_status:
        | "in_stock"
        | "allocated"
        | "installed"
        | "damaged"
        | "returned"
      subscription_status: "trialing" | "active" | "past_due" | "cancelled"
      test_session_status: "running" | "verified" | "failed"
      user_role: "admin" | "employee" | "customer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  waytara: {
    Enums: {
      device_status: ["test", "active", "offline", "decommissioned"],
      invite_status: ["pending", "accepted", "expired", "revoked"],
      lead_status: ["new", "assigned", "quoted", "converted", "lost"],
      onboarding_stage: [
        "quotation_sent",
        "quotation_accepted",
        "payment_pending",
        "account_created",
        "site_setup",
        "connection_test",
        "install_scheduled",
        "install_completed",
      ],
      payment_option: ["full", "split"],
      payment_status: ["pending", "paid", "failed", "refunded"],
      payment_type: ["full", "advance", "balance"],
      plan_code: ["basic", "pro", "advance"],
      power_package: [
        "solar_inverter",
        "solar_battery_inverter",
        "inverter_battery",
        "solar_inverter_ev",
        "solar_battery_inverter_ev",
        "inverter_battery_ev",
        "ev_charger_only",
      ],
      power_source_category: ["grid_tied", "off_grid", "hybrid"],
      property_type: [
        "residential_independent_villas",
        "gated_communities_rwas_high_rises",
        "factories_heavy_engineering_processing_plants",
        "corporate_offices_hospitals_hotels_retail",
        "logistics_delivery_hubs_bus_depots",
        "tech_parks_data_centers_rnd_hubs",
      ],
      quotation_status: [
        "draft",
        "sent",
        "accepted",
        "rejected",
        "expired",
        "revision_requested",
      ],
      stock_status: [
        "in_stock",
        "allocated",
        "installed",
        "damaged",
        "returned",
      ],
      subscription_status: ["trialing", "active", "past_due", "cancelled"],
      test_session_status: ["running", "verified", "failed"],
      user_role: ["admin", "employee", "customer"],
    },
  },
} as const
