"use client";

import * as React from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { DataTable } from "@/components/ui/data-table";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { fmtDate, inr } from "@/lib/savings";
import { pctChange } from "@/lib/reports/period-math";
import type { StatementData } from "@/lib/reports/statement-data";
import type { DayEnergy } from "@/lib/savings";
import { cn } from "@/lib/utils";
import { ChartEmptyState } from "./chart-empty-state";
import { DailyBars } from "./chart-kit";
import { FLOW } from "./flow-colors";
import { fmtKwhText, fmtPct, Panel, StatTile } from "./perf-kit";

const change = (cur: number, prev: number | undefined) => {
  if (prev === undefined) return "—";
  const c = pctChange(cur, prev);
  return c === null ? "—" : `${c > 0 ? "+" : ""}${c.toFixed(0)}%`;
};
const kwh = (n: number) => n.toFixed(1);

/** The month's statement laid out as in the PDF: the four headline figures, then (as graphs) the day-by-day bars or (as tables) the
 *  comparison, the bill, the highlights and every day. */
export function StatementView({ s, view }: { s: StatementData; view: "graph" | "table" }) {
  const c = s.current;
  if (c.days === 0) return <ChartEmptyState label={`No readings in ${s.label}`} />;
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatTile label={`Generated · ${s.label}`} value={fmtKwhText(c.pvKwh)} hint={c.avgPvPerDay !== null ? `${c.avgPvPerDay.toFixed(1)} kWh a day` : undefined} />
        <StatTile label={`Used · ${s.label}`} value={fmtKwhText(c.loadKwh)} hint={`${fmtPct(c.selfSufficiencyPct)} covered by solar`} />
        <StatTile label={`Saved · ${s.label}`} value={inr(s.bill.saved)} hint={s.bill.exact ? "On the month's units" : "An estimate: a share of the month's bill"} tone="good" />
        <StatTile label={`CO₂ avoided · ${s.label}`} value={`${s.co2Kg.toFixed(s.co2Kg >= 100 ? 0 : 1)} kg`} hint={`About ${s.trees.toFixed(1)} trees a year`} />
      </div>
      {view === "graph" ? <Graphs s={s} /> : <Tables s={s} />}
      <p className="text-xs leading-relaxed text-muted-foreground">
        {s.partial ? `${fmtDate(s.from)} to ${fmtDate(s.to)}, month so far · ` : ""}From the inverter&apos;s own counters, not the electricity board&apos;s meter. Tariff: {s.tariffNote}. CO₂: {s.co2Note}.
      </p>
    </div>
  );
}

function Graphs({ s }: { s: StatementData }) {
  const gen = s.daily.map((d) => ({ date: d.day, value: d.pvKwh ?? 0 }));
  const used = s.daily.map((d) => ({ date: d.day, value: d.loadKwh }));
  if (s.daily.length < 2) return <p className="text-sm text-muted-foreground">One day so far this month; the bars appear from the second day.</p>;
  return (
    <div className="grid gap-4 lg:grid-cols-2">
      <Panel chart title={`Generated each day · ${s.label}`} description="Energy the panels made each day.">
        <DailyBars daily={gen} label="Generated" color={FLOW.producing} />
      </Panel>
      <Panel chart title={`Used each day · ${s.label}`} description="Energy the site used each day.">
        <DailyBars daily={used} label="Used" color={FLOW.consuming} />
      </Panel>
    </div>
  );
}

function Tables({ s }: { s: StatementData }) {
  const c = s.current;
  const rows: { name: string; cur: number; prev?: number; last?: number }[] = [
    { name: "Generated by the panels", cur: c.pvKwh, prev: s.previous?.pvKwh, last: s.lastYear?.pvKwh },
    { name: "Used by the site", cur: c.loadKwh, prev: s.previous?.loadKwh, last: s.lastYear?.loadKwh },
    { name: "Bought from the grid", cur: c.importKwh, prev: s.previous?.importKwh, last: s.lastYear?.importKwh },
    { name: "Sent to the grid", cur: c.exportKwh, prev: s.previous?.exportKwh, last: s.lastYear?.exportKwh },
  ];
  const cmp = (cur: number, o: number | undefined) => (o === undefined ? "—" : `${fmtKwhText(o)} (${change(cur, o)})`);
  const columns = React.useMemo<ColumnDef<DayEnergy, unknown>[]>(
    () => [
      { id: "day", accessorFn: (d) => d.day, header: "Day", cell: ({ row }) => fmtDate(row.original.day) },
      { id: "pv", accessorFn: (d) => d.pvKwh ?? 0, header: "Generated", meta: { align: "right" }, cell: ({ row }) => kwh(row.original.pvKwh ?? 0) },
      { id: "load", accessorFn: (d) => d.loadKwh, header: "Used", meta: { align: "right" }, cell: ({ row }) => kwh(row.original.loadKwh) },
      { id: "imp", accessorFn: (d) => d.importKwh, header: "Bought", meta: { align: "right" }, cell: ({ row }) => kwh(row.original.importKwh) },
      { id: "exp", accessorFn: (d) => d.exportKwh, header: "Sent", meta: { align: "right" }, cell: ({ row }) => kwh(row.original.exportKwh) },
    ],
    []
  );
  return (
    <div className="space-y-4">
      <Panel title="Energy, compared" description={s.partial ? "The month so far against the same days of the month before and of a year ago." : "This month against the month before and the same month a year ago."}>
        <div className="overflow-x-auto rounded-lg border border-border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>&nbsp;</TableHead>
                <TableHead className="text-right">{s.label}</TableHead>
                <TableHead className="text-right">{s.partial ? "Month before, same days" : "Month before"}</TableHead>
                <TableHead className="text-right">{s.partial ? "Last year, same days" : "Same month last year"}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {rows.map((r) => (
                <TableRow key={r.name}>
                  <TableCell className="text-foreground">{r.name}</TableCell>
                  <TableCell className="text-right tabular-nums">{fmtKwhText(r.cur)}</TableCell>
                  <TableCell className="text-right tabular-nums text-muted-foreground">{cmp(r.cur, r.prev)}</TableCell>
                  <TableCell className="text-right tabular-nums text-muted-foreground">{cmp(r.cur, r.last)}</TableCell>
                </TableRow>
              ))}
              <TableRow>
                <TableCell className="text-foreground">Solar used on site</TableCell>
                <TableCell className="text-right tabular-nums">{fmtPct(c.selfUsePct)}</TableCell>
                <TableCell className="text-right tabular-nums text-muted-foreground">{fmtPct(s.previous?.selfUsePct ?? null)}</TableCell>
                <TableCell className="text-right tabular-nums text-muted-foreground">{fmtPct(s.lastYear?.selfUsePct ?? null)}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="text-foreground">Home covered by solar</TableCell>
                <TableCell className="text-right tabular-nums">{fmtPct(c.selfSufficiencyPct)}</TableCell>
                <TableCell className="text-right tabular-nums text-muted-foreground">{fmtPct(s.previous?.selfSufficiencyPct ?? null)}</TableCell>
                <TableCell className="text-right tabular-nums text-muted-foreground">{fmtPct(s.lastYear?.selfSufficiencyPct ?? null)}</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </Panel>

      <div className="grid gap-4 lg:grid-cols-2">
        <Panel title="Your electricity bill" description={s.bill.exact ? "Worked out on this month's units and the tariff. Fixed charges and meter rent are left out." : "A share of the month's bill, since the month is not over or some of it has no readings. Fixed charges and meter rent are left out."}>
          <div className="overflow-hidden rounded-lg border border-border">
            <Table>
              <TableBody>
                <TableRow>
                  <TableCell className="text-foreground">Without solar, everything bought from the grid</TableCell>
                  <TableCell className="text-right tabular-nums">{inr(s.bill.withoutSolar)}</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="text-foreground">With solar</TableCell>
                  <TableCell className="text-right tabular-nums">{inr(s.bill.withSolar)}</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium text-foreground">Saved</TableCell>
                  <TableCell className={cn("text-right font-medium tabular-nums", "text-emerald-600 dark:text-emerald-400")}>{inr(s.bill.saved)}</TableCell>
                </TableRow>
                {s.savedSinceCommissioning !== null && (
                  <TableRow>
                    <TableCell className="text-foreground">Saved since the system was commissioned</TableCell>
                    <TableCell className="text-right tabular-nums">{inr(s.savedSinceCommissioning)}</TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </div>
        </Panel>

        <Panel title="Highlights" description={`${c.days} day${c.days === 1 ? "" : "s"} with readings, ${s.completeness}% of the period.`}>
          <div className="overflow-hidden rounded-lg border border-border">
            <Table>
              <TableBody>
                <TableRow>
                  <TableCell className="text-foreground">Best day</TableCell>
                  <TableCell className="text-right tabular-nums">{c.best ? `${fmtDate(c.best.day)}: ${fmtKwhText(c.best.kwh)}` : "—"}</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="text-foreground">Lowest day</TableCell>
                  <TableCell className="text-right tabular-nums">{c.lowest ? `${fmtDate(c.lowest.day)}: ${fmtKwhText(c.lowest.kwh)}` : "—"}</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="text-foreground">Average a day</TableCell>
                  <TableCell className="text-right tabular-nums">{c.avgPvPerDay !== null ? fmtKwhText(c.avgPvPerDay) : "—"}</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="text-foreground">Carbon avoided</TableCell>
                  <TableCell className="text-right tabular-nums">{s.co2Kg.toFixed(1)} kg</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </div>
        </Panel>
      </div>

      <Panel title="Day by day" description="Click a heading to sort. Energy in kWh.">
        <DataTable columns={columns} data={s.daily} pageSize={15} footer={["Total", kwh(c.pvKwh), kwh(c.loadKwh), kwh(c.importKwh), kwh(c.exportKwh)]} />
      </Panel>
    </div>
  );
}
