-- Re-seeds instrument_catalog/device_parameter_map for ev_charger —
-- lost when device_parameters was dropped this session (20260924000300)
-- without ever being carried over from 20260917000000's real OCPP field
-- list. Sourced from that migration plus ev-charger-catalog.ts's enum
-- label lists and instrument-settings-catalog.ts's ev_charger
-- Configuration Keys array — formalizing already-shipped TS knowledge
-- into the shared catalog, not new data. Generated by
-- gen_ev_charger_seed.mjs, not hand-typed.

insert into waytara.instrument_catalog
  (instrument_key, name, category, device_category, unit, description, value_kind,
   direction, min_role, regulated, cadence_seconds, enum_ref, valid_min, valid_max)
values
  ('energy_active_import_register_kwh', 'Energy Import (Total)', 'charging', 'ev_charger', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('power_active_import_w', 'Charging Power', 'charging', 'ev_charger', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('power_offered_w', 'Power Offered', 'charging', 'ev_charger', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('current_import_a', 'Charging Current', 'charging', 'ev_charger', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('voltage_v', 'Line Voltage', 'charging', 'ev_charger', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('soc_pct', 'EV State of Charge', 'charging', 'ev_charger', '%', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, 0, 100),
  ('temperature_c', 'Connector Temperature', 'charging', 'ev_charger', 'degC', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('connector_status', 'Connector Status', 'charging', 'ev_charger', null, null, 'enum', 'read', 'customer'::waytara.user_role, false, 30, 'connector_status', null, null),
  ('error_code', 'Error Code', 'charging', 'ev_charger', null, null, 'enum', 'read', 'customer'::waytara.user_role, false, 30, 'error_code', null, null),
  ('ChargeProfileMaxStackLevel', 'Charge Profile Max Stack Level', 'charging', 'ev_charger', null, null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('SupportedFeatureProfiles', 'Supported Feature Profiles', 'charging', 'ev_charger', null, null, 'text', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('max_charging_current_a', 'Max Charging Current', 'charging', 'ev_charger', 'A', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 6, 32),
  ('HeartbeatInterval', 'Heartbeat Interval', 'charging', 'ev_charger', 's', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 10, null),
  ('MeterValueSampleInterval', 'Meter Value Sample Interval', 'charging', 'ev_charger', 's', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0, null),
  ('MeterValuesSampledData', 'Sampled Measurands', 'charging', 'ev_charger', null, null, 'text', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('MeterValuesAlignedData', 'Clock-Aligned Measurands', 'charging', 'ev_charger', null, null, 'text', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('ClockAlignedDataInterval', 'Clock-Aligned Interval', 'charging', 'ev_charger', 's', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0, null),
  ('ConnectionTimeOut', 'Connection Timeout', 'charging', 'ev_charger', 's', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0, null),
  ('AuthorizeRemoteTxRequests', 'Authorize Remote Start/Stop', 'charging', 'ev_charger', null, null, 'boolean', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('LocalAuthorizeOffline', 'Local Authorize When Offline', 'charging', 'ev_charger', null, null, 'boolean', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('LocalPreAuthorize', 'Local Pre-Authorize', 'charging', 'ev_charger', null, null, 'boolean', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('StopTransactionOnEVSideDisconnect', 'Stop On EV Disconnect', 'charging', 'ev_charger', null, null, 'boolean', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('UnlockConnectorOnEVSideDisconnect', 'Unlock On EV Disconnect', 'charging', 'ev_charger', null, null, 'boolean', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('ResetRetries', 'Reset Retries', 'charging', 'ev_charger', null, null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0, null),
  ('TransactionMessageRetryInterval', 'Transaction Message Retry Interval', 'charging', 'ev_charger', 's', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0, null)
on conflict (instrument_key) do nothing;

insert into waytara.instrument_enum_values (enum_ref, code, label, notes)
values
  ('connector_status', '0', 'Available', null),
  ('connector_status', '1', 'Preparing', null),
  ('connector_status', '2', 'Charging', null),
  ('connector_status', '3', 'Suspended', null),
  ('connector_status', '4', 'Faulted', null),
  ('error_code', '0', 'NoError', null),
  ('error_code', '1', 'ConnectorLockFailure', null),
  ('error_code', '2', 'EVCommunicationError', null),
  ('error_code', '3', 'GroundFailure', null),
  ('error_code', '4', 'HighTemperature', null),
  ('error_code', '5', 'InternalError', null),
  ('error_code', '6', 'LocalListConflict', null),
  ('error_code', '7', 'OtherError', null),
  ('error_code', '8', 'OverCurrentFailure', null),
  ('error_code', '9', 'OverVoltage', null),
  ('error_code', '10', 'PowerMeterFailure', null),
  ('error_code', '11', 'PowerSwitchFailure', null),
  ('error_code', '12', 'ReaderFailure', null),
  ('error_code', '13', 'ResetFailure', null),
  ('error_code', '14', 'UnderVoltage', null),
  ('error_code', '15', 'WeakSignal', null)
on conflict (enum_ref, code) do nothing;

insert into waytara.device_parameter_map
  (stock_id, instrument_key, protocol, address, decode, is_required, is_enabled, verified, notes)
values
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'energy_active_import_register_kwh', 'ocpp_1_6', '{"measurand":"Energy.Active.Import.Register"}'::jsonb, null, true, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'power_active_import_w', 'ocpp_1_6', '{"measurand":"Power.Active.Import"}'::jsonb, null, true, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'power_offered_w', 'ocpp_1_6', '{"measurand":"Power.Offered"}'::jsonb, null, true, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'current_import_a', 'ocpp_1_6', '{"measurand":"Current.Import"}'::jsonb, null, true, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'voltage_v', 'ocpp_1_6', '{"measurand":"Voltage"}'::jsonb, null, true, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'soc_pct', 'ocpp_1_6', '{"measurand":"SoC"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'temperature_c', 'ocpp_1_6', '{"measurand":"Temperature"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'connector_status', 'ocpp_1_6', '{"ocpp_message":"StatusNotification","field":"status"}'::jsonb, null, true, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'error_code', 'ocpp_1_6', '{"ocpp_message":"StatusNotification","field":"errorCode"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'ChargeProfileMaxStackLevel', 'ocpp_1_6', '{"ocpp_key":"ChargeProfileMaxStackLevel"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'SupportedFeatureProfiles', 'ocpp_1_6', '{"ocpp_key":"SupportedFeatureProfiles"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'max_charging_current_a', 'ocpp_1_6', '{"ocpp_mechanism":"SetChargingProfile"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'HeartbeatInterval', 'ocpp_1_6', '{"ocpp_key":"HeartbeatInterval"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'MeterValueSampleInterval', 'ocpp_1_6', '{"ocpp_key":"MeterValueSampleInterval"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'MeterValuesSampledData', 'ocpp_1_6', '{"ocpp_key":"MeterValuesSampledData"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'MeterValuesAlignedData', 'ocpp_1_6', '{"ocpp_key":"MeterValuesAlignedData"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'ClockAlignedDataInterval', 'ocpp_1_6', '{"ocpp_key":"ClockAlignedDataInterval"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'ConnectionTimeOut', 'ocpp_1_6', '{"ocpp_key":"ConnectionTimeOut"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'AuthorizeRemoteTxRequests', 'ocpp_1_6', '{"ocpp_key":"AuthorizeRemoteTxRequests"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'LocalAuthorizeOffline', 'ocpp_1_6', '{"ocpp_key":"LocalAuthorizeOffline"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'LocalPreAuthorize', 'ocpp_1_6', '{"ocpp_key":"LocalPreAuthorize"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'StopTransactionOnEVSideDisconnect', 'ocpp_1_6', '{"ocpp_key":"StopTransactionOnEVSideDisconnect"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'UnlockConnectorOnEVSideDisconnect', 'ocpp_1_6', '{"ocpp_key":"UnlockConnectorOnEVSideDisconnect"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'ResetRetries', 'ocpp_1_6', '{"ocpp_key":"ResetRetries"}'::jsonb, null, false, true, true, null),
  ((select id from waytara.stock where model_number = 'PZ-AC-7.4-T2'), 'TransactionMessageRetryInterval', 'ocpp_1_6', '{"ocpp_key":"TransactionMessageRetryInterval"}'::jsonb, null, false, true, true, null)
on conflict (stock_id, instrument_key) do nothing;

