-- Seed: instrument_catalog + instrument_enum_values + device_parameter_map
-- for the existing live Deye SUN-8K stock row, generated from the three
-- register-map source files (Read/Write/Enum) — not hand-typed, to avoid
-- transcription drift on ~150 rows of register addresses and decode formulas.

insert into waytara.instrument_catalog
  (instrument_key, name, category, device_category, unit, description, value_kind,
   direction, min_role, regulated, cadence_seconds, enum_ref, valid_min, valid_max)
values
  ('day_battery_charge_kwh', 'Battery Charge (Today)', 'battery', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('day_battery_discharge_kwh', 'Battery Discharge (Today)', 'battery', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('battery_temp_c', 'Battery Temperature', 'battery', 'solar_inverter', 'degC', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('battery_voltage_v', 'Battery Voltage', 'battery', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('battery_soc_pct', 'Battery State of Charge', 'battery', 'solar_inverter', '%', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, 0.0, 100.0),
  ('battery_power_w', 'Battery Power', 'battery', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('battery_current_a', 'Battery Current', 'battery', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('bms_charge_voltage_v', 'Bms Charge Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_discharge_voltage_v', 'Bms Discharge Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_charge_current_limit_a', 'Bms Charge Current Limit A', 'battery', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_discharge_current_limit_a', 'Bms Discharge Current Limit A', 'battery', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_soc_pct', 'Bms Soc %', 'battery', 'solar_inverter', '%', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_voltage_v', 'Bms Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_current_a', 'Bms Current A', 'battery', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_temp_c', 'Bms Temp C', 'battery', 'solar_inverter', 'degC', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_alarm_flags', 'Bms Alarm Flags', 'battery', 'solar_inverter', null, null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('bms_fault_flags', 'Bms Fault Flags', 'battery', 'solar_inverter', null, null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('total_battery_charge_kwh', 'Total Battery Charge Energy', 'battery', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('total_battery_discharge_kwh', 'Total Battery Discharge Energy', 'battery', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('sd_status', 'SD Card Logging Status', 'diagnostics', 'solar_inverter', null, null, 'numeric', 'read', 'admin'::waytara.user_role, false, 30, null, null, null),
  ('gen_power_w', 'Gen Power W', 'generator', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('gen_voltage_v', 'Gen Voltage V', 'generator', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('gen_frequency_hz', 'Gen Frequency Hz', 'generator', 'solar_inverter', 'Hz', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('day_reactive_energy_kvarh', 'Day Reactive Energy', 'grid', 'solar_inverter', 'kvarh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('day_grid_import_kwh', 'Day Grid Import Kwh', 'grid', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('day_grid_export_kwh', 'Day Grid Export Kwh', 'grid', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('grid_frequency_hz', 'Grid Frequency', 'grid', 'solar_inverter', 'Hz', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('grid_voltage_v', 'Grid Voltage', 'grid', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('grid_l1_current_a', 'Grid L1 Current A', 'grid', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('grid_l2_current_a', 'Grid L2 Current A', 'grid', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('grid_l1_power_w', 'Grid L1 Power W', 'grid', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('grid_l2_power_w', 'Grid L2 Power', 'grid', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('grid_total_power_w', 'Grid Total Power W', 'grid', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('grid_ct_power_w', 'Grid CT Power', 'grid', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('total_grid_import_kwh', 'Total Grid Import Energy', 'grid', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('grid_connected', 'Grid Connected', 'grid', 'solar_inverter', null, null, 'boolean', 'read', 'customer'::waytara.user_role, false, 5, null, 0.0, 1.0),
  ('total_grid_export_kwh', 'Total Grid Export Energy', 'grid', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('inverter_state', 'Inverter State', 'inverter', 'solar_inverter', null, null, 'enum', 'read', 'customer'::waytara.user_role, false, 5, 'inverter_state', 0.0, 5.0),
  ('day_active_energy_kwh', 'Day Active Energy', 'inverter', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('inverter_dc_temp_c', 'Inverter DC Temperature', 'inverter', 'solar_inverter', 'degC', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('inverter_ac_temp_c', 'Inverter AC Temperature', 'inverter', 'solar_inverter', 'degC', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('ambient_temp_c', 'Ambient Temp C', 'inverter', 'solar_inverter', 'degC', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('inverter_voltage_v', 'Inverter Voltage', 'inverter', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('inverter_current_a', 'Inverter Current', 'inverter', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('inverter_power_w', 'Inverter Power', 'inverter', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('inverter_frequency_hz', 'Inverter Frequency', 'inverter', 'solar_inverter', 'Hz', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('total_active_energy_kwh', 'Total Active Energy', 'inverter', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('day_load_energy_kwh', 'Day Load Energy Kwh', 'load', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('load_l1_power_w', 'Load L1 Power', 'load', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('load_l2_power_w', 'Load L2 Power', 'load', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('load_total_power_w', 'Load Total Power W', 'load', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('load_frequency_hz', 'Load Frequency', 'load', 'solar_inverter', 'Hz', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('total_load_energy_kwh', 'Total Load Energy', 'load', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('day_pv_energy_kwh', 'Day Pv Energy Kwh', 'solar', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('pv1_voltage_v', 'PV String 1 Voltage', 'solar', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('pv1_current_a', 'PV String 1 Current', 'solar', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('pv2_voltage_v', 'PV String 2 Voltage', 'solar', 'solar_inverter', 'V', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('pv2_current_a', 'PV String 2 Current', 'solar', 'solar_inverter', 'A', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('pv1_power_w', 'PV String 1 Power', 'solar', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('pv2_power_w', 'PV String 2 Power', 'solar', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 5, null, null, null),
  ('total_pv_energy_kwh', 'Total PV Energy (Lifetime)', 'solar', 'solar_inverter', 'kWh', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('device_type', 'Device Type', 'system', 'solar_inverter', null, null, 'enum', 'read', 'admin'::waytara.user_role, false, 3600, 'device_type', null, null),
  ('modbus_address', 'Modbus Address', 'system', 'solar_inverter', null, null, 'numeric', 'read', 'admin'::waytara.user_role, false, 3600, null, 1.0, 247.0),
  ('protocol_version', 'Protocol Version', 'system', 'solar_inverter', null, null, 'text', 'read', 'admin'::waytara.user_role, false, 3600, null, null, null),
  ('fault_word_1', 'Fault Word 1', 'system', 'solar_inverter', null, null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('fault_word_2', 'Fault Word 2', 'system', 'solar_inverter', null, null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('fault_word_3', 'Fault Word 3', 'system', 'solar_inverter', null, null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('fault_word_4', 'Fault Word 4', 'system', 'solar_inverter', null, null, 'numeric', 'read', 'customer'::waytara.user_role, false, 30, null, null, null),
  ('rated_power_w', 'Rated Power', 'system', 'solar_inverter', 'W', null, 'numeric', 'read', 'customer'::waytara.user_role, false, 3600, null, null, null),
  ('serial_number', 'Serial Number', 'system', 'solar_inverter', null, null, 'text', 'read', 'customer'::waytara.user_role, false, 3600, null, null, null),
  ('rtc_year_month', 'Rtc Year Month', 'system', 'solar_inverter', null, null, 'text', 'write', 'customer'::waytara.user_role, false, 3600, null, 0.0, 255.0),
  ('rtc_day_hour', 'Rtc Day Hour', 'system', 'solar_inverter', null, null, 'text', 'write', 'customer'::waytara.user_role, false, 3600, null, 1.0, 31.0),
  ('rtc_minute_second', 'Rtc Minute Second', 'system', 'solar_inverter', null, null, 'text', 'write', 'customer'::waytara.user_role, false, 3600, null, 0.0, 59.0),
  ('batt_max_charge_current_a', 'Batt Max Charge Current A', 'battery', 'solar_inverter', 'A', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 185.0),
  ('batt_max_discharge_current_a', 'Batt Max Discharge Current A', 'battery', 'solar_inverter', 'A', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 185.0),
  ('max_solar_power_w', 'Max Solar Power W', 'solar', 'solar_inverter', 'W', null, 'numeric', 'write', 'customer'::waytara.user_role, false, 3600, null, null, null),
  ('battery_type', 'Battery Type', 'battery', 'solar_inverter', null, null, 'enum', 'write', 'customer'::waytara.user_role, false, null, 'battery_type', 0.0, 1.0),
  ('bms_protocol', 'Bms Protocol', 'battery', 'solar_inverter', null, null, 'enum', 'write', 'customer'::waytara.user_role, false, null, 'bms_protocol', null, null),
  ('batt_capacity_ah', 'Batt Capacity Ah', 'battery', 'solar_inverter', 'Ah', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 2000.0),
  ('batt_equalize_voltage_v', 'Batt Equalize Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('batt_absorption_voltage_v', 'Batt Absorption Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('batt_float_voltage_v', 'Batt Float Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('batt_empty_voltage_v', 'Batt Empty Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('equalize_interval_days', 'Equalize Interval Days', 'battery', 'solar_inverter', 'day', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 90.0),
  ('equalize_duration_h', 'Equalize Duration H', 'battery', 'solar_inverter', 'h', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 20.0),
  ('temp_compensation_mv_per_c', 'Temp Compensation Mv Per C', 'battery', 'solar_inverter', 'mV/degC', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 50.0),
  ('batt_control_mode', 'Batt Control Mode', 'battery', 'solar_inverter', null, null, 'enum', 'write', 'customer'::waytara.user_role, false, null, 'batt_control_mode', 0.0, 2.0),
  ('batt_charge_efficiency_pct', 'Batt Charge Efficiency %', 'battery', 'solar_inverter', '%', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('batt_shutdown_soc_pct', 'Batt Shutdown Soc %', 'battery', 'solar_inverter', '%', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('batt_low_soc_pct', 'Batt Low Soc %', 'battery', 'solar_inverter', '%', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('batt_restart_soc_pct', 'Batt Restart Soc %', 'battery', 'solar_inverter', '%', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('batt_shutdown_voltage_v', 'Batt Shutdown Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('batt_low_voltage_v', 'Batt Low Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('batt_restart_voltage_v', 'Batt Restart Voltage V', 'battery', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('grid_charge_enabled', 'Grid Charge Enabled', 'grid', 'solar_inverter', null, null, 'boolean', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 1.0),
  ('grid_charge_start_voltage_v', 'Grid Charge Start Voltage V', 'grid', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('grid_charge_start_soc_pct', 'Grid Charge Start Soc %', 'grid', 'solar_inverter', '%', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('grid_charge_current_a', 'Grid Charge Current A', 'grid', 'solar_inverter', 'A', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 185.0),
  ('gen_charge_enabled', 'Gen Charge Enabled', 'generator', 'solar_inverter', null, null, 'boolean', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 1.0),
  ('gen_charge_start_voltage_v', 'Gen Charge Start Voltage V', 'generator', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('gen_charge_start_soc_pct', 'Gen Charge Start Soc %', 'generator', 'solar_inverter', '%', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('gen_charge_current_a', 'Gen Charge Current A', 'generator', 'solar_inverter', 'A', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 185.0),
  ('gen_max_run_time_h', 'Gen Max Run Time H', 'generator', 'solar_inverter', 'h', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('gen_cooling_time_h', 'Gen Cooling Time H', 'generator', 'solar_inverter', 'h', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('gen_port_function', 'Gen Port Function', 'generator', 'solar_inverter', null, null, 'enum', 'write', 'customer'::waytara.user_role, false, null, 'gen_port_function', 0.0, 2.0),
  ('smartload_off_voltage_v', 'Smartload Off Voltage V', 'generator', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('smartload_off_soc_pct', 'Smartload Off Soc %', 'generator', 'solar_inverter', '%', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('smartload_on_voltage_v', 'Smartload On Voltage V', 'generator', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('smartload_on_soc_pct', 'Smartload On Soc %', 'generator', 'solar_inverter', '%', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('smartload_on_delay_min', 'Smartload On Delay Min', 'generator', 'solar_inverter', 'min', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 1.0, 120.0),
  ('schedule_enable_days', 'Schedule Enable Days', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('tou_slot1_start_time', 'Tou Slot1 Start Time', 'system', 'solar_inverter', null, null, 'text', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 2355.0),
  ('tou_slot2_start_time', 'Tou Slot2 Start Time', 'system', 'solar_inverter', null, null, 'text', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 2355.0),
  ('tou_slot3_start_time', 'Tou Slot3 Start Time', 'system', 'solar_inverter', null, null, 'text', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 2355.0),
  ('tou_slot4_start_time', 'Tou Slot4 Start Time', 'system', 'solar_inverter', null, null, 'text', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 2355.0),
  ('tou_slot5_start_time', 'Tou Slot5 Start Time', 'system', 'solar_inverter', null, null, 'text', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 2355.0),
  ('tou_slot6_start_time', 'Tou Slot6 Start Time', 'system', 'solar_inverter', null, null, 'text', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 2355.0),
  ('tou_slot1_power_w', 'Tou Slot1 Power W', 'system', 'solar_inverter', 'W', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 8000.0),
  ('tou_slot2_power_w', 'Tou Slot2 Power W', 'system', 'solar_inverter', 'W', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 8000.0),
  ('tou_slot3_power_w', 'Tou Slot3 Power W', 'system', 'solar_inverter', 'W', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 8000.0),
  ('tou_slot4_power_w', 'Tou Slot4 Power W', 'system', 'solar_inverter', 'W', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 8000.0),
  ('tou_slot5_power_w', 'Tou Slot5 Power W', 'system', 'solar_inverter', 'W', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 8000.0),
  ('tou_slot6_power_w', 'Tou Slot6 Power W', 'system', 'solar_inverter', 'W', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 8000.0),
  ('tou_slot1_target_voltage_v', 'Tou Slot1 Target Voltage V', 'system', 'solar_inverter', 'V', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('tou_slot2_target_voltage_v', 'Tou Slot2 Target Voltage V', 'system', 'solar_inverter', 'V', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('tou_slot3_target_voltage_v', 'Tou Slot3 Target Voltage V', 'system', 'solar_inverter', 'V', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('tou_slot4_target_voltage_v', 'Tou Slot4 Target Voltage V', 'system', 'solar_inverter', 'V', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('tou_slot5_target_voltage_v', 'Tou Slot5 Target Voltage V', 'system', 'solar_inverter', 'V', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('tou_slot6_target_voltage_v', 'Tou Slot6 Target Voltage V', 'system', 'solar_inverter', 'V', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 38.0, 61.0),
  ('tou_slot1_target_soc_pct', 'Tou Slot1 Target Soc %', 'system', 'solar_inverter', '%', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('tou_slot2_target_soc_pct', 'Tou Slot2 Target Soc %', 'system', 'solar_inverter', '%', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('tou_slot3_target_soc_pct', 'Tou Slot3 Target Soc %', 'system', 'solar_inverter', '%', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('tou_slot4_target_soc_pct', 'Tou Slot4 Target Soc %', 'system', 'solar_inverter', '%', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('tou_slot5_target_soc_pct', 'Tou Slot5 Target Soc %', 'system', 'solar_inverter', '%', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('tou_slot6_target_soc_pct', 'Tou Slot6 Target Soc %', 'system', 'solar_inverter', '%', null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, 0.0, 100.0),
  ('tou_slot1_flags', 'Tou Slot1 Flags', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, null, null),
  ('tou_slot2_flags', 'Tou Slot2 Flags', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, null, null),
  ('tou_slot3_flags', 'Tou Slot3 Flags', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, null, null),
  ('tou_slot4_flags', 'Tou Slot4 Flags', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, null, null),
  ('tou_slot5_flags', 'Tou Slot5 Flags', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, null, null),
  ('tou_slot6_flags', 'Tou Slot6 Flags', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'employee'::waytara.user_role, false, null, null, null, null),
  ('export_limit_mode', 'Export Limit Mode', 'grid', 'solar_inverter', null, null, 'enum', 'write', 'customer'::waytara.user_role, false, null, 'export_limit_mode', 0.0, 2.0),
  ('solar_sell_enabled', 'Solar Sell Enabled', 'solar', 'solar_inverter', null, null, 'boolean', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 1.0),
  ('max_sell_power_w', 'Max Sell Power W', 'grid', 'solar_inverter', 'W', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 8000.0),
  ('zero_export_power_w', 'Zero Export Power W', 'grid', 'solar_inverter', 'W', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('gen_peak_shaving_power_w', 'Gen Peak Shaving Power W', 'generator', 'solar_inverter', 'W', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 16000.0),
  ('grid_peak_shaving_power_w', 'Grid Peak Shaving Power W', 'grid', 'solar_inverter', 'W', null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.0, 16000.0),
  ('output_power_factor', 'Output Power Factor', 'grid', 'solar_inverter', null, null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, 0.8, 1.2),
  ('function_switches', 'Function Switches', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null),
  ('grid_standard', 'Grid Standard', 'grid', 'solar_inverter', null, null, 'enum', 'write', 'customer'::waytara.user_role, true, null, 'grid_standard', null, null),
  ('grid_frequency_setting', 'Grid Frequency Setting', 'grid', 'solar_inverter', null, null, 'enum', 'write', 'customer'::waytara.user_role, true, null, 'grid_frequency_setting', 0.0, 1.0),
  ('grid_ov_trip_v', 'Grid Ov Trip V', 'grid', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, true, null, null, 180.0, 270.0),
  ('grid_uv_trip_v', 'Grid Uv Trip V', 'grid', 'solar_inverter', 'V', null, 'numeric', 'write', 'customer'::waytara.user_role, true, null, null, 180.0, 270.0),
  ('grid_of_trip_hz', 'Grid Of Trip Hz', 'grid', 'solar_inverter', 'Hz', null, 'numeric', 'write', 'customer'::waytara.user_role, true, null, null, 45.0, 65.0),
  ('grid_uf_trip_hz', 'Grid Uf Trip Hz', 'grid', 'solar_inverter', 'Hz', null, 'numeric', 'write', 'customer'::waytara.user_role, true, null, null, 45.0, 65.0),
  ('display_settings', 'Display Settings', 'system', 'solar_inverter', null, null, 'numeric', 'write', 'customer'::waytara.user_role, false, null, null, null, null)
on conflict (instrument_key) do nothing;

insert into waytara.instrument_enum_values (enum_ref, code, label, notes)
values
  ('inverter_state', '0', 'Standby', 'DISCREPANCY: V1 (hybrid map) and Deye''s V133 doc disagree at code 5 — V1 says ''activating'', V133 says ''Turn off''. These are opposite meanings. Confirm against this unit''s LCD before relying on code 5 for anything user-facing.'),
  ('inverter_state', '1', 'Self-check', null),
  ('inverter_state', '2', 'Normal', null),
  ('inverter_state', '3', 'Alarm', null),
  ('inverter_state', '4', 'Fault (V1) / Failure (V133)', null),
  ('inverter_state', '5', 'Activating (V1) / Turn off (V133)', null),
  ('device_type', '0x0200', 'String/hybrid inverter family (observed on this unit)', 'Not a small enumerated list — a hex identifier used to select the profile file at runtime. Only one value has been observed; other device_type codes exist across Deye''s product range but aren''t catalogued here.'),
  ('battery_type', '0', 'Lead-acid', 'Confirmed [OK].'),
  ('battery_type', '1', 'Lithium', null),
  ('batt_control_mode', '0', 'By voltage', 'Confirmed [OK]. Decides which threshold set (voltage vs SOC) is active elsewhere in the settings.'),
  ('batt_control_mode', '1', 'By SOC', null),
  ('batt_control_mode', '2', 'No battery', null),
  ('gen_port_function', '0', 'Generator input', 'Confirmed [OK]. Gates the whole generator settings panel.'),
  ('gen_port_function', '1', 'Smart-load output', null),
  ('gen_port_function', '2', 'Micro-inverter input', null),
  ('export_limit_mode', '0', 'Sell to grid', 'Confirmed [OK]. The old map mistakenly typed this register as watts — it''s an enum, not a power value.'),
  ('export_limit_mode', '1', 'Limit via built-in CT', null),
  ('export_limit_mode', '2', 'Limit via external meter', null),
  ('grid_frequency_setting', '0', '50 Hz', 'Confirmed [OK]. Regulated setting — requires the confirmation-before-write step, plus a write-log entry.'),
  ('grid_frequency_setting', '1', '60 Hz', null),
  ('bms_protocol', '0', 'General CAN (only value observed on this unit)', 'Full list NOT available — the reference map only notes ''enum, list in V110 register 223'', a document we don''t have. Only code 0 has been sampled. Do not build a full picker until the complete list is sourced.'),
  ('grid_standard', '1', 'INMETRO', 'Full list sourced from Deye''s V133 doc (more complete than the hybrid map, which only said ''[1,21], see V110 appendix 4'' with no list). Code 19 repeats ''EN50549'' (same as code 2) verbatim in Deye''s own document — likely a copy-paste error in their source, not a transcription mistake here; confirm on the unit''s LCD before treating 19 as a distinct standard. Valid range in the hybrid map was [1,21] but V133 goes up to 22 — recheck the range too. Regulated setting: requires confirmation-before-write plus a write-log entry.'),
  ('grid_standard', '2', 'EN50549', null),
  ('grid_standard', '3', 'EN50438', null),
  ('grid_standard', '4', 'IEC61727', null),
  ('grid_standard', '5', 'CUSTOM', null),
  ('grid_standard', '6', 'VDE_AR_N_4105', null),
  ('grid_standard', '7', 'UTE_C15_712_1', null),
  ('grid_standard', '8', 'RD_1699', null),
  ('grid_standard', '9', 'CEI_0_21', null),
  ('grid_standard', '10', 'G98_G99', null),
  ('grid_standard', '11', 'AS4777', null),
  ('grid_standard', '12', 'NB/T 32004', null),
  ('grid_standard', '13', 'AS4777.2 Australia A', null),
  ('grid_standard', '14', 'AS4777.2 Australia B', null),
  ('grid_standard', '15', 'AS4777.2 Australia C', null),
  ('grid_standard', '16', 'AS4777.2 New Zealand', null),
  ('grid_standard', '17', 'MEA', null),
  ('grid_standard', '18', 'PEA', null),
  ('grid_standard', '19', 'EN50549 (repeated — see note)', null),
  ('grid_standard', '20', 'VDE4105', null),
  ('grid_standard', '21', 'R25', null),
  ('grid_standard', '22', 'CEI-016', null)
on conflict (enum_ref, code) do nothing;

insert into waytara.device_parameter_map
  (stock_id, instrument_key, protocol, address, decode, is_required, is_enabled, verified, notes)
values
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'day_battery_charge_kwh', 'modbus_tcp', '{"registers": [70]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'day_battery_discharge_kwh', 'modbus_tcp', '{"registers": [71]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'battery_temp_c', 'modbus_tcp', '{"registers": [182]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, false, 'v * 0.1   [NO 1000 offset, unlike 90/91/319]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'battery_voltage_v', 'modbus_tcp', '{"registers": [183]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'battery_soc_pct', 'modbus_tcp', '{"registers": [184]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'battery_power_w', 'modbus_tcp', '{"registers": [190]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'battery_current_a', 'modbus_tcp', '{"registers": [191]}'::jsonb, '{"scale": 0.01, "signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v) * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_charge_voltage_v', 'modbus_tcp', '{"registers": [312]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_discharge_voltage_v', 'modbus_tcp', '{"registers": [313]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, false, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_charge_current_limit_a', 'modbus_tcp', '{"registers": [314]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_discharge_current_limit_a', 'modbus_tcp', '{"registers": [315]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_soc_pct', 'modbus_tcp', '{"registers": [316]}'::jsonb, null, false, true, true, 'v * 1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_voltage_v', 'modbus_tcp', '{"registers": [317]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_current_a', 'modbus_tcp', '{"registers": [318]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_temp_c', 'modbus_tcp', '{"registers": [319]}'::jsonb, '{"offset": -1000, "scale": 0.1}'::jsonb, false, true, true, '(v-1000)/10'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_alarm_flags', 'modbus_tcp', '{"registers": [322]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, 'bit tests'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_fault_flags', 'modbus_tcp', '{"registers": [323]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, 'bit tests'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'total_battery_charge_kwh', 'modbus_tcp', '{"registers": [72, 73]}'::jsonb, '{"scale": 0.1, "combine": "low_high_word", "low_word_register": 72}'::jsonb, false, true, true, '((v[73]<<16) | v[72]) * 0.1  [low word at 72]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'total_battery_discharge_kwh', 'modbus_tcp', '{"registers": [74, 75]}'::jsonb, '{"scale": 0.1, "combine": "low_high_word", "low_word_register": 74}'::jsonb, false, true, true, '((v[75]<<16) | v[74]) * 0.1  [low word at 74]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'sd_status', 'modbus_tcp', '{"registers": [92]}'::jsonb, null, false, true, false, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_power_w', 'modbus_tcp', '{"registers": [166]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_voltage_v', 'modbus_tcp', '{"registers": [181]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_frequency_hz', 'modbus_tcp', '{"registers": [196]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'day_reactive_energy_kvarh', 'modbus_tcp', '{"registers": [61]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, false, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'day_grid_import_kwh', 'modbus_tcp', '{"registers": [76]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'day_grid_export_kwh', 'modbus_tcp', '{"registers": [77]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_frequency_hz', 'modbus_tcp', '{"registers": [79]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_voltage_v', 'modbus_tcp', '{"registers": [150]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_l1_current_a', 'modbus_tcp', '{"registers": [160]}'::jsonb, '{"scale": 0.01, "signed": true}'::jsonb, false, true, false, '(v>=32768 ? v-65536 : v) * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_l2_current_a', 'modbus_tcp', '{"registers": [161]}'::jsonb, '{"scale": 0.01, "signed": true}'::jsonb, false, true, false, '(v>=32768 ? v-65536 : v) * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_l1_power_w', 'modbus_tcp', '{"registers": [167]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_l2_power_w', 'modbus_tcp', '{"registers": [168]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_total_power_w', 'modbus_tcp', '{"registers": [169]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_ct_power_w', 'modbus_tcp', '{"registers": [172]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'total_grid_import_kwh', 'modbus_tcp', '{"registers": [78]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, false, '((high<<16) | v[78]) * 0.1 - HIGH WORD UNRESOLVED'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_connected', 'modbus_tcp', '{"registers": [194]}'::jsonb, null, false, true, false, 'v != 0'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'total_grid_export_kwh', 'modbus_tcp', '{"registers": [81, 82]}'::jsonb, '{"scale": 0.1, "combine": "low_high_word", "low_word_register": 81}'::jsonb, false, true, false, '((v[82]<<16) | v[81]) * 0.1  [low word at 81]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'inverter_state', 'modbus_tcp', '{"registers": [59]}'::jsonb, null, false, true, true, 'map[v]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'day_active_energy_kwh', 'modbus_tcp', '{"registers": [60]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'inverter_dc_temp_c', 'modbus_tcp', '{"registers": [90]}'::jsonb, '{"offset": -1000, "scale": 0.1}'::jsonb, false, true, true, '(v - 1000) / 10'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'inverter_ac_temp_c', 'modbus_tcp', '{"registers": [91]}'::jsonb, '{"offset": -1000, "scale": 0.1}'::jsonb, false, true, true, '(v - 1000) / 10'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'ambient_temp_c', 'modbus_tcp', '{"registers": [95]}'::jsonb, '{"offset": -1000, "scale": 0.1}'::jsonb, false, true, false, '(v - 1000) / 10'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'inverter_voltage_v', 'modbus_tcp', '{"registers": [154]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'inverter_current_a', 'modbus_tcp', '{"registers": [164]}'::jsonb, '{"scale": 0.01, "signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v) * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'inverter_power_w', 'modbus_tcp', '{"registers": [175]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'inverter_frequency_hz', 'modbus_tcp', '{"registers": [193]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'total_active_energy_kwh', 'modbus_tcp', '{"registers": [63, 64]}'::jsonb, '{"scale": 0.1, "combine": "low_high_word", "low_word_register": 63}'::jsonb, false, true, true, '((v[64]<<16) | v[63]) * 0.1  [low word at 63]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'day_load_energy_kwh', 'modbus_tcp', '{"registers": [84]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'load_l1_power_w', 'modbus_tcp', '{"registers": [176]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'load_l2_power_w', 'modbus_tcp', '{"registers": [177]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'load_total_power_w', 'modbus_tcp', '{"registers": [178]}'::jsonb, '{"signed": true}'::jsonb, false, true, true, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'load_frequency_hz', 'modbus_tcp', '{"registers": [192]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'total_load_energy_kwh', 'modbus_tcp', '{"registers": [85, 86]}'::jsonb, '{"scale": 0.1, "combine": "low_high_word", "low_word_register": 85}'::jsonb, false, true, true, '((v[86]<<16) | v[85]) * 0.1  [low word at 85]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'day_pv_energy_kwh', 'modbus_tcp', '{"registers": [108]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'pv1_voltage_v', 'modbus_tcp', '{"registers": [109]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'pv1_current_a', 'modbus_tcp', '{"registers": [110]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'pv2_voltage_v', 'modbus_tcp', '{"registers": [111]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'pv2_current_a', 'modbus_tcp', '{"registers": [112]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'pv1_power_w', 'modbus_tcp', '{"registers": [186]}'::jsonb, null, false, true, true, 'v * 1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'pv2_power_w', 'modbus_tcp', '{"registers": [187]}'::jsonb, null, false, true, true, 'v * 1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'total_pv_energy_kwh', 'modbus_tcp', '{"registers": [96, 97]}'::jsonb, '{"scale": 0.1, "combine": "low_high_word", "low_word_register": 96}'::jsonb, false, true, true, '((v[97]<<16) | v[96]) * 0.1  [low word at 96]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'device_type', 'modbus_tcp', '{"registers": [0]}'::jsonb, null, false, true, true, 'hex code'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'modbus_address', 'modbus_tcp', '{"registers": [1]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'protocol_version', 'modbus_tcp', '{"registers": [2]}'::jsonb, null, false, true, true, '{v>>8}.{v & 0xFF}'''),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'fault_word_1', 'modbus_tcp', '{"registers": [103]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, '16 independent bits; report as word 1 bit N'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'fault_word_2', 'modbus_tcp', '{"registers": [104]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, '16 independent bits; report as word 2 bit N'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'fault_word_3', 'modbus_tcp', '{"registers": [105]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, '16 independent bits; report as word 3 bit N'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'fault_word_4', 'modbus_tcp', '{"registers": [106]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, '16 independent bits; report as word 4 bit N'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'rated_power_w', 'modbus_tcp', '{"registers": [16, 17]}'::jsonb, '{"scale": 0.1, "combine": "low_high_word", "low_word_register": 16}'::jsonb, false, true, true, '((v[17]<<16) | v[16]) * 0.1  [low word at 16]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'serial_number', 'modbus_tcp', '{"registers": [3, 4, 5, 6, 7]}'::jsonb, null, false, true, true, 'chr(v>>8) + chr(v & 0xFF) for each of 3,4,5,6,7'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'rtc_year_month', 'modbus_tcp', '{"registers": [22]}'::jsonb, null, false, true, true, 'year = 2000 + (v>>8); month = v & 0xFF'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'rtc_day_hour', 'modbus_tcp', '{"registers": [23]}'::jsonb, null, false, true, true, 'day = v>>8; hour = v & 0xFF'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'rtc_minute_second', 'modbus_tcp', '{"registers": [24]}'::jsonb, null, false, true, true, 'minute = v>>8; second = v & 0xFF'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_max_charge_current_a', 'modbus_tcp', '{"registers": [210]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_max_discharge_current_a', 'modbus_tcp', '{"registers": [211]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'max_solar_power_w', 'modbus_tcp', '{"registers": [53]}'::jsonb, null, false, true, false, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'battery_type', 'modbus_tcp', '{"registers": [200]}'::jsonb, null, false, true, true, 'map[v]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'bms_protocol', 'modbus_tcp', '{"registers": [325]}'::jsonb, null, false, true, true, 'map[v]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_capacity_ah', 'modbus_tcp', '{"registers": [204]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_equalize_voltage_v', 'modbus_tcp', '{"registers": [201]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_absorption_voltage_v', 'modbus_tcp', '{"registers": [202]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_float_voltage_v', 'modbus_tcp', '{"registers": [203]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_empty_voltage_v', 'modbus_tcp', '{"registers": [205]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, false, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'equalize_interval_days', 'modbus_tcp', '{"registers": [207]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'equalize_duration_h', 'modbus_tcp', '{"registers": [208]}'::jsonb, '{"scale": 0.5}'::jsonb, false, true, true, 'v * 0.5'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'temp_compensation_mv_per_c', 'modbus_tcp', '{"registers": [209]}'::jsonb, '{"signed": true}'::jsonb, false, true, false, '(v>=32768 ? v-65536 : v)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_control_mode', 'modbus_tcp', '{"registers": [213]}'::jsonb, null, false, true, true, 'map[v]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_charge_efficiency_pct', 'modbus_tcp', '{"registers": [216]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_shutdown_soc_pct', 'modbus_tcp', '{"registers": [217]}'::jsonb, null, false, true, true, 'v * 1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_low_soc_pct', 'modbus_tcp', '{"registers": [219]}'::jsonb, null, false, true, true, 'v * 1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_restart_soc_pct', 'modbus_tcp', '{"registers": [218]}'::jsonb, null, false, true, true, 'v * 1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_shutdown_voltage_v', 'modbus_tcp', '{"registers": [220]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_low_voltage_v', 'modbus_tcp', '{"registers": [222]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'batt_restart_voltage_v', 'modbus_tcp', '{"registers": [221]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_charge_enabled', 'modbus_tcp', '{"registers": [232]}'::jsonb, null, false, true, true, 'v != 0'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_charge_start_voltage_v', 'modbus_tcp', '{"registers": [228]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_charge_start_soc_pct', 'modbus_tcp', '{"registers": [229]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_charge_current_a', 'modbus_tcp', '{"registers": [230]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_charge_enabled', 'modbus_tcp', '{"registers": [231]}'::jsonb, null, false, true, true, 'v != 0'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_charge_start_voltage_v', 'modbus_tcp', '{"registers": [225]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_charge_start_soc_pct', 'modbus_tcp', '{"registers": [226]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_charge_current_a', 'modbus_tcp', '{"registers": [227]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_max_run_time_h', 'modbus_tcp', '{"registers": [223]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_cooling_time_h', 'modbus_tcp', '{"registers": [224]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, false, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_port_function', 'modbus_tcp', '{"registers": [235]}'::jsonb, null, false, true, true, 'map[v]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'smartload_off_voltage_v', 'modbus_tcp', '{"registers": [236]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'smartload_off_soc_pct', 'modbus_tcp', '{"registers": [237]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'smartload_on_voltage_v', 'modbus_tcp', '{"registers": [238]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'smartload_on_soc_pct', 'modbus_tcp', '{"registers": [239]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'smartload_on_delay_min', 'modbus_tcp', '{"registers": [294]}'::jsonb, null, false, true, false, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'schedule_enable_days', 'modbus_tcp', '{"registers": [248]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, true, 'bit0 = schedule enabled; bits 1-7 = Mon..Sun; bit8 = Spain mode'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot1_start_time', 'modbus_tcp', '{"registers": [250]}'::jsonb, null, false, true, true, 'hour = v//100; minute = v%100'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot2_start_time', 'modbus_tcp', '{"registers": [251]}'::jsonb, null, false, true, true, 'hour = v//100; minute = v%100'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot3_start_time', 'modbus_tcp', '{"registers": [252]}'::jsonb, null, false, true, true, 'hour = v//100; minute = v%100'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot4_start_time', 'modbus_tcp', '{"registers": [253]}'::jsonb, null, false, true, true, 'hour = v//100; minute = v%100'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot5_start_time', 'modbus_tcp', '{"registers": [254]}'::jsonb, null, false, true, true, 'hour = v//100; minute = v%100'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot6_start_time', 'modbus_tcp', '{"registers": [255]}'::jsonb, null, false, true, true, 'hour = v//100; minute = v%100'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot1_power_w', 'modbus_tcp', '{"registers": [256]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot2_power_w', 'modbus_tcp', '{"registers": [257]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot3_power_w', 'modbus_tcp', '{"registers": [258]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot4_power_w', 'modbus_tcp', '{"registers": [259]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot5_power_w', 'modbus_tcp', '{"registers": [260]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot6_power_w', 'modbus_tcp', '{"registers": [261]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot1_target_voltage_v', 'modbus_tcp', '{"registers": [262]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot2_target_voltage_v', 'modbus_tcp', '{"registers": [263]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot3_target_voltage_v', 'modbus_tcp', '{"registers": [264]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot4_target_voltage_v', 'modbus_tcp', '{"registers": [265]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot5_target_voltage_v', 'modbus_tcp', '{"registers": [266]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot6_target_voltage_v', 'modbus_tcp', '{"registers": [267]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot1_target_soc_pct', 'modbus_tcp', '{"registers": [268]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot2_target_soc_pct', 'modbus_tcp', '{"registers": [269]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot3_target_soc_pct', 'modbus_tcp', '{"registers": [270]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot4_target_soc_pct', 'modbus_tcp', '{"registers": [271]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot5_target_soc_pct', 'modbus_tcp', '{"registers": [272]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot6_target_soc_pct', 'modbus_tcp', '{"registers": [273]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot1_flags', 'modbus_tcp', '{"registers": [274]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, 'bit0 = charge from grid; bit1 = charge from generator; bit2 = unknown, set on all six slots'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot2_flags', 'modbus_tcp', '{"registers": [275]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, 'bit0 = charge from grid; bit1 = charge from generator; bit2 = unknown, set on all six slots'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot3_flags', 'modbus_tcp', '{"registers": [276]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, 'bit0 = charge from grid; bit1 = charge from generator; bit2 = unknown, set on all six slots'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot4_flags', 'modbus_tcp', '{"registers": [277]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, 'bit0 = charge from grid; bit1 = charge from generator; bit2 = unknown, set on all six slots'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot5_flags', 'modbus_tcp', '{"registers": [278]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, 'bit0 = charge from grid; bit1 = charge from generator; bit2 = unknown, set on all six slots'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'tou_slot6_flags', 'modbus_tcp', '{"registers": [279]}'::jsonb, '{"note": "raw diagnostic mask \u2014 bit-level meaning not yet decomposed into named sub-fields"}'::jsonb, false, true, false, 'bit0 = charge from grid; bit1 = charge from generator; bit2 = unknown, set on all six slots'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'export_limit_mode', 'modbus_tcp', '{"registers": [244]}'::jsonb, null, false, true, true, 'map[v]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'solar_sell_enabled', 'modbus_tcp', '{"registers": [247]}'::jsonb, null, false, true, true, 'v != 0'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'max_sell_power_w', 'modbus_tcp', '{"registers": [245]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'zero_export_power_w', 'modbus_tcp', '{"registers": [206]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'gen_peak_shaving_power_w', 'modbus_tcp', '{"registers": [292]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_peak_shaving_power_w', 'modbus_tcp', '{"registers": [293]}'::jsonb, null, false, true, true, 'v'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'output_power_factor', 'modbus_tcp', '{"registers": [295]}'::jsonb, '{"scale": 0.001}'::jsonb, false, true, true, 'v * 0.001'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'function_switches', 'modbus_tcp', '{"registers": [280]}'::jsonb, '{"note": "2-bit packed sub-fields \u2014 raw register value only for phase 1"}'::jsonb, false, true, false, '8 two-bit fields. 11 = enabled, 10 = disabled, 00 or 01 = NO ACTION (MCU ignores it)'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_standard', 'modbus_tcp', '{"registers": [284]}'::jsonb, null, false, true, true, 'map[v]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_frequency_setting', 'modbus_tcp', '{"registers": [285]}'::jsonb, null, false, true, true, 'map[v]'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_ov_trip_v', 'modbus_tcp', '{"registers": [287]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_uv_trip_v', 'modbus_tcp', '{"registers": [288]}'::jsonb, '{"scale": 0.1}'::jsonb, false, true, true, 'v * 0.1'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_of_trip_hz', 'modbus_tcp', '{"registers": [289]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'grid_uf_trip_hz', 'modbus_tcp', '{"registers": [290]}'::jsonb, '{"scale": 0.01}'::jsonb, false, true, true, 'v * 0.01'),
  ((select id from waytara.stock where model_number = 'SUN-8K-SG01LP1-EU'), 'display_settings', 'modbus_tcp', '{"registers": [330]}'::jsonb, '{"note": "2-bit packed sub-fields \u2014 raw register value only for phase 1"}'::jsonb, false, true, false, 'bits 0-1 time_sync; 2-3 beep; 4-5 am_pm; 6-7 auto_dim; 14-15 allow_remote. 11=on, 10=off, 00/01=no action')
on conflict (stock_id, instrument_key) do nothing;
