-- State electricity tariffs: slabs, free units, duty - read from https://electricbill.in/en/tariffs (one page per state, each citing
-- the regulator's order) and, for the free-unit schemes, from news reports of the government orders. EVERY row is "indicative":
-- the figures are as that site lists them and have NOT been checked against the order itself, and the site contradicts itself in
-- places (duty, meter rent, a headline rate that fits only the lifeline category). Each row's note names the order it cites and the
-- inconsistencies seen. The admin app's Electricity rates page is where a row is replaced by one checked against the order and
-- marked verified.
--
-- Left out because no usable source was found: Bihar, Goa, Punjab, Meghalaya, Mizoram, Nagaland, Sikkim, Ladakh, Lakshadweep,
-- Dadra and Nagar Haveli and Daman and Diu. A customer there keeps using the rate set on their own account.
--
-- This replaces the first flat 'indicative' rates (midpoints of ranges quoted by aggregator sites) that were only a placeholder.

delete from waytara.electricity_tariffs where confidence = 'indicative' and source_url not like 'https://electricbill.in/%';

insert into waytara.electricity_tariffs
  (state, category, rate_per_kwh, slabs, billing_months, duty_pct, surcharge_per_kwh, free_units, free_units_cap, free_units_over_cap, effective_from, source_url, source_note, confidence) values
  ('Andaman and Nicobar Islands', 'residential', 6.86, '[{"upTo":100,"rate":4.2},{"upTo":200,"rate":7.5},{"upTo":500,"rate":10.9},{"upTo":1000,"rate":11.9},{"upTo":null,"rate":12.9}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/andaman-nicobar', 'As listed on electricbill.in, which cites: JERC / A&N Electricity Department tariff (urjapay.andamannicobar.gov.in/Tariff). Service-II (standard) domestic. Duty not stated, taken as 0. The page headline says a uniform Rs 3.00, which only fits Service-I (lifeline). Not checked against the order itself.', 'indicative'),
  ('Andaman and Nicobar Islands', 'commercial', 15.30, '[{"upTo":100,"rate":12.5},{"upTo":200,"rate":15.5},{"upTo":null,"rate":20.5}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/andaman-nicobar', 'As listed on electricbill.in, which cites: JERC / A&N Electricity Department tariff. Non-domestic Service-I. Duty not stated, taken as 0. Not checked against the order itself.', 'indicative'),
  ('Andaman and Nicobar Islands', 'industrial', 11.00, '[{"upTo":null,"rate":11.0}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/andaman-nicobar', 'As listed on electricbill.in, which cites: JERC / A&N Electricity Department tariff. LT Industrial Service-I. Duty not stated, taken as 0. Not checked against the order itself.', 'indicative'),
  ('Andhra Pradesh', 'residential', 5.24, '[{"upTo":30,"rate":1.9},{"upTo":75,"rate":3.0},{"upTo":125,"rate":4.5},{"upTo":225,"rate":6.0},{"upTo":400,"rate":8.75},{"upTo":null,"rate":9.75}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/andhra-pradesh', 'As listed on electricbill.in, which cites: APERC tariff order 2026-27 (apspdcl.in). Duty 6% per the table. Not checked against the order itself.', 'indicative'),
  ('Andhra Pradesh', 'commercial', 8.52, '[{"upTo":50,"rate":5.4},{"upTo":100,"rate":7.65},{"upTo":300,"rate":9.05},{"upTo":500,"rate":9.6},{"upTo":null,"rate":9.95}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/andhra-pradesh', 'As listed on electricbill.in, which cites: APERC tariff order 2026-27. Not checked against the order itself.', 'indicative'),
  ('Andhra Pradesh', 'industrial', 7.10, '[{"upTo":null,"rate":6.7}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/andhra-pradesh', 'As listed on electricbill.in, which cites: APERC tariff order 2026-27. Industry (general), LT. Not checked against the order itself.', 'indicative'),
  ('Arunachal Pradesh', 'residential', 4.40, '[{"upTo":null,"rate":4.4}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/arunachal-pradesh', 'As listed on electricbill.in, which cites: APSERC ARR and retail tariff notice FY 2026-27. General domestic LT (Rs 3.00 is the BPL/Kutir Jyoti rate). Duty not stated, taken as 0. Not checked against the order itself.', 'indicative'),
  ('Arunachal Pradesh', 'commercial', 5.65, '[{"upTo":null,"rate":5.65}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/arunachal-pradesh', 'As listed on electricbill.in, which cites: APSERC retail tariff notice FY 2026-27. Duty not stated, taken as 0. Not checked against the order itself.', 'indicative'),
  ('Arunachal Pradesh', 'industrial', 4.95, '[{"upTo":null,"rate":4.95}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/arunachal-pradesh', 'As listed on electricbill.in, which cites: APSERC retail tariff notice FY 2026-27. Duty not stated, taken as 0. Not checked against the order itself.', 'indicative'),
  ('Assam', 'residential', 5.62, '[{"upTo":120,"rate":4.25},{"upTo":240,"rate":6.3},{"upTo":300,"rate":7.2},{"upTo":500,"rate":7.4},{"upTo":null,"rate":8.19}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/assam', 'As listed on electricbill.in, which cites: AERC / APDCL tariff notice FY 2026-27. LT-II Domestic-A (0.5-5 kW). Not checked against the order itself.', 'indicative'),
  ('Assam', 'commercial', 9.39, '[{"upTo":null,"rate":8.94}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/assam', 'As listed on electricbill.in, which cites: AERC / APDCL tariff notice FY 2026-27. LT-IV Commercial (0.5-30 kW). Not checked against the order itself.', 'indicative'),
  ('Assam', 'industrial', 6.92, '[{"upTo":null,"rate":6.59}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/assam', 'As listed on electricbill.in, which cites: AERC / APDCL tariff notice FY 2026-27. LT-VIII(i) small industries, rural (urban is 6.84). Not checked against the order itself.', 'indicative'),
  ('Chandigarh', 'residential', 3.64, '[{"upTo":100,"rate":2.95},{"upTo":200,"rate":3.75},{"upTo":300,"rate":4.8},{"upTo":400,"rate":5.0},{"upTo":null,"rate":5.4}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/chandigarh', 'As listed on electricbill.in, which cites: JERC approved tariff schedule (chandigarhpower.com). LTDS-II. Duty not stated, taken as 0. The page headline says a uniform Rs 2.90, which only fits LTDS-I. Not checked against the order itself.', 'indicative'),
  ('Chandigarh', 'commercial', 4.91, '[{"upTo":100,"rate":4.6},{"upTo":200,"rate":4.8},{"upTo":null,"rate":5.75}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/chandigarh', 'As listed on electricbill.in, which cites: JERC approved tariff schedule. NDS-I. Not checked against the order itself.', 'indicative'),
  ('Chandigarh', 'industrial', 4.50, '[{"upTo":500,"rate":4.5},{"upTo":1000,"rate":4.6},{"upTo":null,"rate":4.7}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/chandigarh', 'As listed on electricbill.in, which cites: JERC approved tariff schedule. LTIS-I. Not checked against the order itself.', 'indicative'),
  ('Chhattisgarh', 'residential', 5.00, '[{"upTo":100,"rate":4.4},{"upTo":200,"rate":4.5},{"upTo":400,"rate":6.0},{"upTo":600,"rate":7.0},{"upTo":null,"rate":8.8}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/chhattisgarh', 'As listed on electricbill.in, which cites: CSERC / CSPDCL tariff schedule FY 2026-27. Not checked against the order itself.', 'indicative'),
  ('Chhattisgarh', 'commercial', 7.52, '[{"upTo":100,"rate":6.5},{"upTo":400,"rate":7.6},{"upTo":null,"rate":9.1}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/chhattisgarh', 'As listed on electricbill.in, which cites: CSERC / CSPDCL tariff schedule FY 2026-27. LV-2.1 (single phase up to 5 kW). Not checked against the order itself.', 'indicative'),
  ('Delhi', 'residential', 3.46, '[{"upTo":200,"rate":3.0},{"upTo":400,"rate":4.5},{"upTo":800,"rate":6.5},{"upTo":1200,"rate":7.0},{"upTo":null,"rate":8.0}]'::jsonb, 1, 5, 0.0, 200, 200, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/delhi', 'As listed on electricbill.in, which cites: DERC (page links the FY 2021-22 BSES schedule - check the latest order). Free units: the Delhi government pays the bill of homes using up to 200 units a month (opt-in); between 201 and 400 units it pays half up to Rs 800, which is NOT modelled, so a 201-400 unit home is shown paying a little more than it does. The page links a 2021-22 schedule, so the slabs may be out of date. Not checked against the order itself.', 'indicative'),
  ('Delhi', 'commercial', 8.93, '[{"upTo":null,"rate":8.5}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/delhi', 'As listed on electricbill.in, which cites: DERC (page links the FY 2021-22 BSES schedule). Above 3 kVA (up to 3 kVA is Rs 6.00). Not checked against the order itself.', 'indicative'),
  ('Delhi', 'industrial', 8.14, '[{"upTo":null,"rate":7.75}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/delhi', 'As listed on electricbill.in, which cites: DERC (page links the FY 2021-22 BSES schedule). Not checked against the order itself.', 'indicative'),
  ('Gujarat', 'residential', 7.24, '[{"upTo":50,"rate":3.05},{"upTo":100,"rate":3.5},{"upTo":250,"rate":4.15},{"upTo":null,"rate":5.2}]'::jsonb, 1, 15, 2.5, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/gujarat', 'As listed on electricbill.in, which cites: GERC order for FY 2026-27 (UGVCL-2584-2025, 25 Mar 2026). Urban residential. The Rs 2.50 per unit fuel adjustment charge shown on the page is included; it changes quarterly. Rates are UGVCL (north Gujarat) - other Gujarat distribution companies are close but not identical. Not checked against the order itself.', 'indicative'),
  ('Gujarat', 'commercial', 8.75, '[{"upTo":null,"rate":4.5}]'::jsonb, 1, 25, 2.5, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/gujarat', 'As listed on electricbill.in, which cites: GERC order for FY 2026-27 (UGVCL). Commercial up to 40 kW. Fuel adjustment Rs 2.50 per unit included. Not checked against the order itself.', 'indicative'),
  ('Haryana', 'residential', 3.87, '[{"upTo":150,"rate":2.95},{"upTo":300,"rate":5.25},{"upTo":500,"rate":6.45},{"upTo":null,"rate":7.1}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/haryana', 'As listed on electricbill.in, which cites: HERC (uhbvn.org.in tariff document). Category II, load up to 5 kW. Duty not stated, taken as 0. Not checked against the order itself.', 'indicative'),
  ('Haryana', 'commercial', 6.45, '[{"upTo":null,"rate":6.45}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/haryana', 'As listed on electricbill.in, which cites: HERC (uhbvn.org.in tariff document). LT commercial up to 10 kW. Duty not stated, taken as 0. Not checked against the order itself.', 'indicative'),
  ('Himachal Pradesh', 'residential', 6.18, '[{"upTo":60,"rate":4.71},{"upTo":125,"rate":5.44},{"upTo":null,"rate":5.89}]'::jsonb, 1, 4, 0.45, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/himachal-pradesh', 'As listed on electricbill.in, which cites: HPERC (hpseb.in tariff page). General domestic, with the Rs 0.45 fuel adjustment. The 125 free units for ration-card/BPL homes are NOT applied (eligibility depends on the connection). The page also says duty is 5%. Not checked against the order itself.', 'indicative'),
  ('Himachal Pradesh', 'commercial', 6.71, '[{"upTo":null,"rate":6.39}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/himachal-pradesh', 'As listed on electricbill.in, which cites: HPERC (hpseb.in tariff page). Not checked against the order itself.', 'indicative'),
  ('Himachal Pradesh', 'industrial', 6.00, '[{"upTo":null,"rate":5.71}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/himachal-pradesh', 'As listed on electricbill.in, which cites: HPERC (hpseb.in tariff page). Small industrial power up to 20 kVA. Not checked against the order itself.', 'indicative'),
  ('Jammu and Kashmir', 'residential', 3.08, '[{"upTo":200,"rate":2.45},{"upTo":400,"rate":4.2},{"upTo":null,"rate":4.6}]'::jsonb, 1, 10, 0.0, 0, null, 0, '2026-09-01', 'https://electricbill.in/en/tariffs/jammu-kashmir', 'As listed on electricbill.in, which cites: JERC Order No. 06 of 2026 (JPDCL and KPDCL retail supply tariff FY 2026-27). Metered domestic. Effective 1 Sep 2026 per the page. Not checked against the order itself.', 'indicative'),
  ('Jammu and Kashmir', 'commercial', 4.55, '[{"upTo":200,"rate":3.75},{"upTo":null,"rate":5.7}]'::jsonb, 1, 10, 0.0, 0, null, 0, '2026-09-01', 'https://electricbill.in/en/tariffs/jammu-kashmir', 'As listed on electricbill.in, which cites: JERC Order No. 06 of 2026. Not checked against the order itself.', 'indicative'),
  ('Jharkhand', 'residential', 7.84, '[{"upTo":null,"rate":7.4}]'::jsonb, 1, 6, 0.0, 200, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/jharkhand', 'As listed on electricbill.in, which cites: JSERC / JBVNL tariff FY 2026-27 (Mukhyamantri Urja Khushhali Yojana). Urban. First 200 units free under the state scheme (pending bills of eligible homes are also waived). Rural is Rs 7.20. Not checked against the order itself.', 'indicative'),
  ('Jharkhand', 'commercial', 7.74, '[{"upTo":null,"rate":7.3}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/jharkhand', 'As listed on electricbill.in, which cites: JSERC / JBVNL tariff FY 2026-27. Urban, above 5 kW (rural is 6.70). Not checked against the order itself.', 'indicative'),
  ('Jharkhand', 'industrial', 7.00, '[{"upTo":null,"rate":6.6}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/jharkhand', 'As listed on electricbill.in, which cites: JSERC / JBVNL tariff FY 2026-27. LTIS up to 100 kVA. Not checked against the order itself.', 'indicative'),
  ('Karnataka', 'residential', 6.32, '[{"upTo":null,"rate":5.8}]'::jsonb, 1, 9, 0.0, 200, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/karnataka', 'As listed on electricbill.in, which cites: KERC / BESCOM tariff. The first 200 units are free under Gruha Jyothi for registered homes whose average use is within 200 units; the page shows a single 5.80 slab although its FAQ hints at higher slabs - check the order. Not checked against the order itself.', 'indicative'),
  ('Karnataka', 'commercial', 7.41, '[{"upTo":null,"rate":6.8}]'::jsonb, 1, 9, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/karnataka', 'As listed on electricbill.in, which cites: KERC / BESCOM tariff. LT-3a. Not checked against the order itself.', 'indicative'),
  ('Karnataka', 'industrial', 4.80, '[{"upTo":null,"rate":4.4}]'::jsonb, 1, 9, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/karnataka', 'As listed on electricbill.in, which cites: KERC / BESCOM tariff. LT-5 (MSME, workshops). Not checked against the order itself.', 'indicative'),
  ('Kerala', 'residential', 6.30, '[{"upTo":50,"rate":3.35},{"upTo":100,"rate":4.25},{"upTo":150,"rate":5.35},{"upTo":200,"rate":7.2},{"upTo":250,"rate":8.5},{"upTo":null,"rate":8.5}]'::jsonb, 1, 10, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/kerala', 'As listed on electricbill.in, which cites: KSERC tariff revision 2025-27 (kseb.in). APPROXIMATION: KSEB uses telescopic rates up to 250 units a month, and ABOVE 250 a different table where every unit is charged at the band reached (6.75-9.20). Above 250 units this model keeps the 250-unit rate for the extra units. Not checked against the order itself.', 'indicative'),
  ('Kerala', 'commercial', 7.30, '[{"upTo":100,"rate":6.05},{"upTo":200,"rate":6.8},{"upTo":300,"rate":7.5},{"upTo":500,"rate":8.15},{"upTo":null,"rate":9.4}]'::jsonb, 1, 10, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/kerala', 'As listed on electricbill.in, which cites: KSERC tariff revision 2025-27 (kseb.in). LT-VII(A). The page lists these as non-telescopic (all units at the band reached); shown here telescopic. Not checked against the order itself.', 'indicative'),
  ('Kerala', 'industrial', 6.49, '[{"upTo":null,"rate":5.9}]'::jsonb, 1, 10, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/kerala', 'As listed on electricbill.in, which cites: KSERC tariff revision 2025-27 (kseb.in). LT-IV(A). Not checked against the order itself.', 'indicative'),
  ('Madhya Pradesh', 'residential', 6.57, '[{"upTo":50,"rate":4.71},{"upTo":150,"rate":5.67},{"upTo":300,"rate":7.05},{"upTo":null,"rate":7.24}]'::jsonb, 1, 9, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/madhya-pradesh', 'As listed on electricbill.in, which cites: MPERC tariff FY 2026-27 (mpcz.in). Urban metered. The page also says duty is 12%. Not checked against the order itself.', 'indicative'),
  ('Madhya Pradesh', 'commercial', 8.96, '[{"upTo":50,"rate":6.8},{"upTo":null,"rate":8.3}]'::jsonb, 1, 12, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/madhya-pradesh', 'As listed on electricbill.in, which cites: MPERC tariff FY 2026-27. LV-2.2 shops/offices up to 10 kW. Not checked against the order itself.', 'indicative'),
  ('Madhya Pradesh', 'industrial', 7.76, '[{"upTo":null,"rate":7.05}]'::jsonb, 1, 10, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/madhya-pradesh', 'As listed on electricbill.in, which cites: MPERC tariff FY 2026-27. LV-4.1a. Not checked against the order itself.', 'indicative'),
  ('Maharashtra', 'residential', 11.21, '[{"upTo":100,"rate":3.96},{"upTo":300,"rate":10.8},{"upTo":500,"rate":15.03},{"upTo":null,"rate":17.53}]'::jsonb, 1, 16, 1.6, 0, null, 0, '2025-04-01', 'https://electricbill.in/en/tariffs/maharashtra', 'As listed on electricbill.in, which cites: MERC order, Case No. 75 of 2025. LT I(B) residential; the Rs 1.60 per unit wheeling charge is included. The page also says duty is 21%. Not checked against the order itself.', 'indicative'),
  ('Maharashtra', 'commercial', 12.23, '[{"upTo":null,"rate":8.51}]'::jsonb, 1, 21, 1.6, 0, null, 0, '2025-04-01', 'https://electricbill.in/en/tariffs/maharashtra', 'As listed on electricbill.in, which cites: MERC order, Case No. 75 of 2025. LT II(A) up to 20 kW; wheeling included. Not checked against the order itself.', 'indicative'),
  ('Maharashtra', 'industrial', 9.51, '[{"upTo":null,"rate":6.26}]'::jsonb, 1, 21, 1.6, 0, null, 0, '2025-04-01', 'https://electricbill.in/en/tariffs/maharashtra', 'As listed on electricbill.in, which cites: MERC order, Case No. 75 of 2025. LT V(i) up to 20 kW; wheeling included. Not checked against the order itself.', 'indicative'),
  ('Manipur', 'residential', 6.37, '[{"upTo":100,"rate":5.36},{"upTo":200,"rate":6.25},{"upTo":null,"rate":7.1}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/manipur', 'As listed on electricbill.in, which cites: JERC for Manipur and Mizoram (jerc.gov.in). Domestic supply. The page also says duty is 6%. Not checked against the order itself.', 'indicative'),
  ('Manipur', 'commercial', 8.09, '[{"upTo":100,"rate":7.07},{"upTo":200,"rate":7.85},{"upTo":null,"rate":8.3}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/manipur', 'As listed on electricbill.in, which cites: JERC for Manipur and Mizoram. Not checked against the order itself.', 'indicative'),
  ('Manipur', 'industrial', 6.46, '[{"upTo":null,"rate":6.15}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/manipur', 'As listed on electricbill.in, which cites: JERC for Manipur and Mizoram. Cottage and small industry. Not checked against the order itself.', 'indicative'),
  ('Odisha', 'residential', 4.72, '[{"upTo":50,"rate":2.9},{"upTo":200,"rate":4.7},{"upTo":400,"rate":5.7},{"upTo":null,"rate":6.1}]'::jsonb, 1, 4, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/odisha', 'As listed on electricbill.in, which cites: OERC tariff order FY 2026-27 (orierc.org). The page also says duty is 6%. Not checked against the order itself.', 'indicative'),
  ('Odisha', 'commercial', 6.95, '[{"upTo":100,"rate":5.9},{"upTo":300,"rate":7.0},{"upTo":null,"rate":7.6}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/odisha', 'As listed on electricbill.in, which cites: OERC tariff order FY 2026-27. General purpose LT. Not checked against the order itself.', 'indicative'),
  ('Odisha', 'industrial', 6.51, '[{"upTo":null,"rate":6.2}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/odisha', 'As listed on electricbill.in, which cites: OERC tariff order FY 2026-27. LT industrial. Not checked against the order itself.', 'indicative'),
  ('Puducherry', 'residential', 4.55, '[{"upTo":100,"rate":2.9},{"upTo":200,"rate":4.2},{"upTo":300,"rate":6.2},{"upTo":400,"rate":7.7},{"upTo":null,"rate":7.9}]'::jsonb, 1, 5, 0.25, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/puducherry', 'As listed on electricbill.in, which cites: JERC / Puducherry Electricity Department (electricity.py.gov.in). LTDS-II with the fuel adjustment charge (Rs 0.25 in the table, Rs 0.40 in the text). Not checked against the order itself.', 'indicative'),
  ('Puducherry', 'commercial', 7.80, '[{"upTo":100,"rate":6.25},{"upTo":200,"rate":7.3},{"upTo":null,"rate":8.05}]'::jsonb, 1, 5, 0.4, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/puducherry', 'As listed on electricbill.in, which cites: JERC / Puducherry Electricity Department. Not checked against the order itself.', 'indicative'),
  ('Puducherry', 'industrial', 8.19, '[{"upTo":500,"rate":7.4},{"upTo":1000,"rate":7.65},{"upTo":null,"rate":7.9}]'::jsonb, 1, 5, 0.4, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/puducherry', 'As listed on electricbill.in, which cites: JERC / Puducherry Electricity Department. Not checked against the order itself.', 'indicative'),
  ('Rajasthan', 'residential', 6.15, '[{"upTo":50,"rate":4.75},{"upTo":150,"rate":6.0},{"upTo":300,"rate":7.0},{"upTo":500,"rate":7.0},{"upTo":null,"rate":7.5}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/rajasthan', 'As listed on electricbill.in, which cites: RERC tariff order (jankalyanfile.rajasthan.gov.in). DS/LT-1. Electricity duty (0.4-0.6%) and the fuel charge are not included. Not checked against the order itself.', 'indicative'),
  ('Rajasthan', 'commercial', 7.90, '[{"upTo":100,"rate":7.0},{"upTo":null,"rate":8.5}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/rajasthan', 'As listed on electricbill.in, which cites: RERC tariff order. NDS/LT-2 up to 5 kW. Not checked against the order itself.', 'indicative'),
  ('Rajasthan', 'industrial', 6.00, '[{"upTo":null,"rate":6.0}]'::jsonb, 1, 0.0, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/rajasthan', 'As listed on electricbill.in, which cites: RERC tariff order. SP/LT-5 up to 25 HP. Not checked against the order itself.', 'indicative'),
  ('Tamil Nadu', 'residential', 5.55, '[{"upTo":400,"rate":4.95},{"upTo":500,"rate":6.65},{"upTo":600,"rate":8.8},{"upTo":800,"rate":9.95},{"upTo":1000,"rate":11.05},{"upTo":null,"rate":12.15}]'::jsonb, 2, 5, 0.0, 100, null, 0, '2025-07-01', 'https://electricbill.in/en/tariffs/tamil-nadu', 'As listed on electricbill.in, which cites: TNERC Tariff Order No. 6 of 2025. Bills every two months; slabs are per bill. The first 100 units were free under the earlier scheme. Duty 5% per the page. Not checked against the order itself.', 'indicative'),
  ('Tamil Nadu', 'residential', 5.55, '[{"upTo":400,"rate":4.95},{"upTo":500,"rate":6.65},{"upTo":600,"rate":8.8},{"upTo":800,"rate":9.95},{"upTo":1000,"rate":11.05},{"upTo":null,"rate":12.15}]'::jsonb, 2, 5, 0.0, 200, 500, 100, '2026-05-10', 'https://electricbill.in/en/tariffs/tamil-nadu', 'As listed on electricbill.in, which cites: TNERC Tariff Order No. 6 of 2025 slabs + G.O. (Ms) No. 50 of 10 May 2026 (Energy Department); TNERC Order No. 5 of 2026. From 10 May 2026 homes using up to 500 units in a two-month bill get 200 units free; above 500 units only the earlier 100 free units apply (a sharp cut-off). Duty 5% per the page; news reports of bills fit this only roughly. Not checked against the order itself.', 'indicative'),
  ('Tamil Nadu', 'commercial', 10.17, '[{"upTo":100,"rate":6.65},{"upTo":null,"rate":10.45}]'::jsonb, 2, 5, 0.0, 0, null, 0, '2025-07-01', 'https://electricbill.in/en/tariffs/tamil-nadu', 'As listed on electricbill.in, which cites: TNERC Tariff Order No. 6 of 2025. LT-V (general purpose / miscellaneous), per two-month bill; fixed charge Rs 110-608/kW not modelled. Check this is the right category for your premises. Not checked against the order itself.', 'indicative'),
  ('Tamil Nadu', 'industrial', 8.66, '[{"upTo":null,"rate":8.25}]'::jsonb, 2, 5, 0.0, 0, null, 0, '2025-07-01', 'https://electricbill.in/en/tariffs/tamil-nadu', 'As listed on electricbill.in, which cites: TNERC Tariff Order No. 6 of 2025. LT-III(B) industries and IT services, per two-month bill. Not checked against the order itself.', 'indicative'),
  ('Telangana', 'residential', 5.96, '[{"upTo":200,"rate":5.1},{"upTo":300,"rate":7.7},{"upTo":400,"rate":9.0},{"upTo":800,"rate":9.5},{"upTo":null,"rate":10.0}]'::jsonb, 1, 6, 0.0, 200, 200, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/telangana', 'As listed on electricbill.in, which cites: TGERC tariff (tgsouthernpower.org). LT-I(C), used when a home uses over 200 units. Gruha Jyothi: homes with a white ration card (registered, Aadhaar-linked) using up to 200 units a month pay nothing; over 200 the whole bill is charged. The page shows duty as 6% in the table and 8% in the notes. Not checked against the order itself.', 'indicative'),
  ('Telangana', 'commercial', 10.09, '[{"upTo":100,"rate":8.5},{"upTo":300,"rate":9.9},{"upTo":500,"rate":10.4},{"upTo":null,"rate":11.0}]'::jsonb, 1, 8, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/telangana', 'As listed on electricbill.in, which cites: TGERC tariff (tgsouthernpower.org). LT-II(B) non-domestic above 50 units. Not checked against the order itself.', 'indicative'),
  ('Telangana', 'industrial', 8.16, '[{"upTo":null,"rate":7.7}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/telangana', 'As listed on electricbill.in, which cites: TGERC tariff (tgsouthernpower.org). LT-III. Not checked against the order itself.', 'indicative'),
  ('Tripura', 'residential', 6.79, '[{"upTo":50,"rate":4.86},{"upTo":150,"rate":6.41},{"upTo":300,"rate":7.32},{"upTo":null,"rate":8.52}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/tripura', 'As listed on electricbill.in, which cites: TPERC / TSECL tariff order 2026-27. Domestic general, single phase. Not checked against the order itself.', 'indicative'),
  ('Tripura', 'commercial', 8.05, '[{"upTo":150,"rate":7.21},{"upTo":null,"rate":8.34}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/tripura', 'As listed on electricbill.in, which cites: TPERC / TSECL tariff order 2026-27. Not checked against the order itself.', 'indicative'),
  ('Tripura', 'industrial', 7.62, '[{"upTo":null,"rate":7.26}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/tripura', 'As listed on electricbill.in, which cites: TPERC / TSECL tariff order 2026-27. Up to 5 HP, urban. Not checked against the order itself.', 'indicative'),
  ('Uttar Pradesh', 'residential', 5.99, '[{"upTo":150,"rate":5.5},{"upTo":300,"rate":6.0},{"upTo":null,"rate":6.5}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/uttar-pradesh', 'As listed on electricbill.in, which cites: UPERC / UPPCL tariff FY 2026-27 (uppcl.org). LMV-1 urban. The page also says duty is 7.5%; the link is labelled as a press note. Not checked against the order itself.', 'indicative'),
  ('Uttar Pradesh', 'commercial', 8.06, '[{"upTo":300,"rate":7.5},{"upTo":null,"rate":8.4}]'::jsonb, 1, 7.5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/uttar-pradesh', 'As listed on electricbill.in, which cites: UPERC / UPPCL tariff FY 2026-27. LMV-2 urban up to 4 kW. Not checked against the order itself.', 'indicative'),
  ('Uttar Pradesh', 'industrial', 7.85, '[{"upTo":null,"rate":7.3}]'::jsonb, 1, 7.5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/uttar-pradesh', 'As listed on electricbill.in, which cites: UPERC / UPPCL tariff FY 2026-27. LMV-6 urban. Not checked against the order itself.', 'indicative'),
  ('Uttarakhand', 'residential', 5.24, '[{"upTo":100,"rate":3.65},{"upTo":200,"rate":5.25},{"upTo":400,"rate":7.15},{"upTo":null,"rate":7.8}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/uttarakhand', 'As listed on electricbill.in, which cites: UERC / UPCL tariff (cdnbbsr.s3waas.gov.in, April 2026). RTS-1. Not checked against the order itself.', 'indicative'),
  ('Uttarakhand', 'commercial', 8.14, '[{"upTo":null,"rate":7.75}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2026-04-01', 'https://electricbill.in/en/tariffs/uttarakhand', 'As listed on electricbill.in, which cites: UERC / UPCL tariff. RTS-2 up to 25 kW. Not checked against the order itself.', 'indicative'),
  ('West Bengal', 'residential', 6.33, '[{"upTo":102,"rate":5.04},{"upTo":180,"rate":6.33},{"upTo":300,"rate":7.12},{"upTo":600,"rate":7.52},{"upTo":900,"rate":7.69},{"upTo":null,"rate":9.22}]'::jsonb, 1, 5, 0.0, 0, null, 0, '2025-04-01', 'https://electricbill.in/en/tariffs/west-bengal', 'As listed on electricbill.in, which cites: WBERC / WBSEDCL gist of tariff order 2025-26. Urban domestic. The page is dated 2026 but links the 2025-26 order. The page also says duty is 6%. Not checked against the order itself.', 'indicative'),
  ('West Bengal', 'commercial', 6.64, '[{"upTo":180,"rate":5.77},{"upTo":300,"rate":7.52},{"upTo":450,"rate":8.2},{"upTo":900,"rate":8.51},{"upTo":null,"rate":9.02}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2025-04-01', 'https://electricbill.in/en/tariffs/west-bengal', 'As listed on electricbill.in, which cites: WBERC / WBSEDCL gist of tariff order 2025-26. Not checked against the order itself.', 'indicative'),
  ('West Bengal', 'industrial', 5.54, '[{"upTo":500,"rate":5.23},{"upTo":2000,"rate":7.86},{"upTo":null,"rate":7.83}]'::jsonb, 1, 6, 0.0, 0, null, 0, '2025-04-01', 'https://electricbill.in/en/tariffs/west-bengal', 'As listed on electricbill.in, which cites: WBERC / WBSEDCL gist of tariff order 2025-26. Urban. The page lists a lower 2001+ rate than 501-2000 - check the order. Not checked against the order itself.', 'indicative')
on conflict (state, category, effective_from) do nothing;

-- Record every rate that is already in force as an already-announced change, so the daily job does not e-mail customers about rates
-- that were simply loaded today (it tells people about a change that comes AFTER these).
insert into waytara.tariff_changes (tariff_id, state, category, old_rate, new_rate, effective_from, notified_at)
select t.id, t.state, t.category,
       lag(t.rate_per_kwh) over (partition by t.state, t.category order by t.effective_from),
       t.rate_per_kwh, t.effective_from, now()
from waytara.electricity_tariffs t
where t.effective_from <= current_date
on conflict (tariff_id) do nothing;
