#!/usr/bin/env node
// Regenerates src/types.ts from the live Supabase project schema.
// Run via `pnpm db:types` from the repo root (or this package).
//
// Requires:
//   - SUPABASE_PROJECT_ID   the project ref, i.e. the <ref> in https://<ref>.supabase.co
//   - CLI auth: either run `npx supabase login` once on this machine, or
//     export SUPABASE_ACCESS_TOKEN (a personal access token from
//     https://supabase.com/dashboard/account/tokens) for this shell.

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const projectId = process.env.SUPABASE_PROJECT_ID;

if (!projectId) {
  console.error(
    "[db:types] Missing SUPABASE_PROJECT_ID.\n" +
      "  Set it to your project ref (the <ref> in https://<ref>.supabase.co) and re-run:\n" +
      "    SUPABASE_PROJECT_ID=xxxxxxxx pnpm db:types"
  );
  process.exit(1);
}

const outFile = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../src/types.ts"
);

console.log(`[db:types] Generating types for schema "waytara" from project ${projectId}...`);

const result = spawnSync(
  "npx",
  [
    "--yes",
    "supabase",
    "gen",
    "types",
    "typescript",
    "--project-id",
    projectId,
    "--schema",
    "waytara",
  ],
  { encoding: "utf8", shell: process.platform === "win32" }
);

if (result.error) {
  console.error("[db:types] Failed to run the Supabase CLI:", result.error.message);
  process.exit(1);
}

if (result.status !== 0) {
  console.error(
    result.stderr ||
      "[db:types] `supabase gen types` failed. Are you logged in? Run `npx supabase login` or set SUPABASE_ACCESS_TOKEN."
  );
  process.exit(result.status ?? 1);
}

const banner =
  `// AUTO-GENERATED by \`pnpm db:types\` — do not edit by hand.\n` +
  `// Source: supabase gen types typescript --project-id ${projectId} --schema waytara\n` +
  `// Regenerate after schema migrations: SUPABASE_PROJECT_ID=${projectId} pnpm db:types\n\n`;

writeFileSync(outFile, banner + result.stdout);
console.log(`[db:types] Wrote ${outFile}`);
