import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { PdfLogo } from "./pdf-logo-image";
import { fmtDate } from "@/lib/savings";
import { pctChange } from "./period-math";
import type { StatementData } from "./statement-data";

const styles = StyleSheet.create({
  page: { padding: 40, paddingBottom: 60, fontSize: 10, fontFamily: "Helvetica", color: "#0F172A" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 20 },
  brand: { fontSize: 18, fontWeight: 700, color: "#16A34A" },
  meta: { textAlign: "right", color: "#475569" },
  title: { fontSize: 13, fontWeight: 700, color: "#0F172A" },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 11, fontWeight: 700, marginBottom: 6 },
  statsRow: { flexDirection: "row", gap: 10 },
  statBox: { flex: 1, borderRadius: 4, backgroundColor: "#F8FAFC", padding: 10 },
  statLabel: { color: "#64748B", fontSize: 8, marginBottom: 4 },
  statValue: { fontSize: 14, fontWeight: 700 },
  statHint: { color: "#64748B", fontSize: 8, marginTop: 3 },
  row: { flexDirection: "row" },
  label: { color: "#64748B", width: 100 },
  value: { flex: 1 },
  table: { marginTop: 2, borderTop: "1 solid #E2E8F0" },
  tableRow: { flexDirection: "row", borderBottom: "1 solid #E2E8F0", paddingVertical: 5 },
  tableHead: { flexDirection: "row", paddingVertical: 5, backgroundColor: "#F8FAFC", fontWeight: 700 },
  cName: { flex: 3 },
  cNum: { flex: 2, textAlign: "right" },
  note: { color: "#64748B", fontSize: 8, marginTop: 4 },
  footer: { position: "absolute", bottom: 28, left: 40, right: 40, fontSize: 7.5, color: "#94A3B8" },
});

const kwh = (n: number | null | undefined) => (n === null || n === undefined ? "-" : `${n.toFixed(n >= 100 ? 0 : 1)} kWh`);
const pct = (n: number | null) => (n === null ? "-" : `${n.toFixed(0)}%`);
// "Rs." not the rupee sign: the PDF's base Helvetica font has no glyph for it (it prints a stray character).
const inr = (n: number) => `${n < 0 ? "-" : ""}Rs. ${Math.abs(n).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const change = (cur: number, prev: number) => {
  const c = pctChange(cur, prev);
  return c === null ? "-" : `${c > 0 ? "+" : ""}${c.toFixed(0)}%`;
};
const dayShort = (d: string) => new Date(`${d}T00:00:00Z`).toLocaleDateString("en-IN", { day: "numeric", month: "short", timeZone: "UTC" });

function Footer({ s }: { s: StatementData }) {
  return (
    <Text style={styles.footer} fixed>
      Figures come from the inverter&apos;s own counters, not the electricity board&apos;s meter, and are estimates. Tariff: {s.tariffNote}. CO2: {s.co2Note}. Times are IST.
    </Text>
  );
}

function Statement({ s }: { s: StatementData }) {
  const c = s.current;
  const metrics: { name: string; cur: number; prev?: number; last?: number }[] = [
    { name: "Generated by the panels", cur: c.pvKwh, prev: s.previous?.pvKwh, last: s.lastYear?.pvKwh },
    { name: "Used by the site", cur: c.loadKwh, prev: s.previous?.loadKwh, last: s.lastYear?.loadKwh },
    { name: "Bought from the grid", cur: c.importKwh, prev: s.previous?.importKwh, last: s.lastYear?.importKwh },
    { name: "Sent to the grid", cur: c.exportKwh, prev: s.previous?.exportKwh, last: s.lastYear?.exportKwh },
  ];
  const cmp = (cur: number, other: number | undefined) => (other === undefined ? "-" : `${kwh(other)} (${change(cur, other)})`);
  const period = s.partial ? `${fmtDate(s.from)} to ${fmtDate(s.to)}, month so far` : `${fmtDate(s.from)} to ${fmtDate(s.to)}`;
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <PdfLogo />
            <Text style={styles.title}>Monthly energy statement</Text>
          </View>
          <View style={styles.meta}>
            <Text>{s.label}</Text>
            <Text>Generated {new Date(s.generatedAt).toLocaleDateString("en-IN")}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.label}>Customer</Text>
            <Text style={styles.value}>{s.customerName}</Text>
          </View>
          {s.siteName && (
            <View style={styles.row}>
              <Text style={styles.label}>Site</Text>
              <Text style={styles.value}>{s.siteName}</Text>
            </View>
          )}
          {s.deviceLabel && (
            <View style={styles.row}>
              <Text style={styles.label}>Device</Text>
              <Text style={styles.value}>{s.deviceLabel}</Text>
            </View>
          )}
          <View style={styles.row}>
            <Text style={styles.label}>Period</Text>
            <Text style={styles.value}>{period}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Days with readings</Text>
            <Text style={styles.value}>
              {c.days} · {s.completeness}% of the period
            </Text>
          </View>
        </View>

        <View style={styles.section}>
          <View style={styles.statsRow}>
            <View style={styles.statBox}>
              <Text style={styles.statLabel}>GENERATED</Text>
              <Text style={styles.statValue}>{kwh(c.pvKwh)}</Text>
              <Text style={styles.statHint}>{c.avgPvPerDay !== null ? `${c.avgPvPerDay.toFixed(1)} kWh a day` : " "}</Text>
            </View>
            <View style={styles.statBox}>
              <Text style={styles.statLabel}>USED</Text>
              <Text style={styles.statValue}>{kwh(c.loadKwh)}</Text>
              <Text style={styles.statHint}>{pct(c.selfSufficiencyPct)} covered by solar</Text>
            </View>
            <View style={styles.statBox}>
              <Text style={styles.statLabel}>SAVED{s.bill.exact ? "" : " (ESTIMATE)"}</Text>
              <Text style={styles.statValue}>{inr(s.bill.saved)}</Text>
              <Text style={styles.statHint}>on the electricity bill</Text>
            </View>
            <View style={styles.statBox}>
              <Text style={styles.statLabel}>CO2 AVOIDED</Text>
              <Text style={styles.statValue}>{s.co2Kg.toFixed(0)} kg</Text>
              <Text style={styles.statHint}>about {s.trees.toFixed(1)} trees a year</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Energy, compared</Text>
          <View style={styles.table}>
            <View style={styles.tableHead}>
              <Text style={styles.cName}> </Text>
              <Text style={styles.cNum}>{s.label}</Text>
              <Text style={styles.cNum}>{s.partial ? "Month before, same days" : "Month before"}</Text>
              <Text style={styles.cNum}>{s.partial ? "Last year, same days" : "Same month last year"}</Text>
            </View>
            {metrics.map((m) => (
              <View style={styles.tableRow} key={m.name}>
                <Text style={styles.cName}>{m.name}</Text>
                <Text style={styles.cNum}>{kwh(m.cur)}</Text>
                <Text style={styles.cNum}>{cmp(m.cur, m.prev)}</Text>
                <Text style={styles.cNum}>{cmp(m.cur, m.last)}</Text>
              </View>
            ))}
            <View style={styles.tableRow}>
              <Text style={styles.cName}>Solar used on site</Text>
              <Text style={styles.cNum}>{pct(c.selfUsePct)}</Text>
              <Text style={styles.cNum}>{pct(s.previous?.selfUsePct ?? null)}</Text>
              <Text style={styles.cNum}>{pct(s.lastYear?.selfUsePct ?? null)}</Text>
            </View>
            <View style={styles.tableRow}>
              <Text style={styles.cName}>Home covered by solar</Text>
              <Text style={styles.cNum}>{pct(c.selfSufficiencyPct)}</Text>
              <Text style={styles.cNum}>{pct(s.previous?.selfSufficiencyPct ?? null)}</Text>
              <Text style={styles.cNum}>{pct(s.lastYear?.selfSufficiencyPct ?? null)}</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Your electricity bill</Text>
          <View style={styles.table}>
            <View style={styles.tableRow}>
              <Text style={styles.cName}>Without solar, everything bought from the grid</Text>
              <Text style={styles.cNum}>{inr(s.bill.withoutSolar)}</Text>
            </View>
            <View style={styles.tableRow}>
              <Text style={styles.cName}>With solar</Text>
              <Text style={styles.cNum}>{inr(s.bill.withSolar)}</Text>
            </View>
            <View style={styles.tableRow}>
              <Text style={styles.cName}>Saved</Text>
              <Text style={styles.cNum}>{inr(s.bill.saved)}</Text>
            </View>
            {s.savedSinceCommissioning !== null && (
              <View style={styles.tableRow}>
                <Text style={styles.cName}>Saved since the system was commissioned</Text>
                <Text style={styles.cNum}>{inr(s.savedSinceCommissioning)}</Text>
              </View>
            )}
          </View>
          <Text style={styles.note}>
            {s.bill.exact
              ? "Worked out on this month's units and the tariff below."
              : "The month is not over, or some of it has no readings: this is that share of the month's bill, an estimate."}{" "}
            Fixed charges and meter rent are left out.
          </Text>
        </View>

        {c.best && c.lowest && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Highlights</Text>
            <View style={styles.row}>
              <Text style={styles.label}>Best day</Text>
              <Text style={styles.value}>
                {fmtDate(c.best.day)}: {kwh(c.best.kwh)}
              </Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>Lowest day</Text>
              <Text style={styles.value}>
                {fmtDate(c.lowest.day)}: {kwh(c.lowest.kwh)}
              </Text>
            </View>
          </View>
        )}

        <Footer s={s} />
      </Page>

      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Day by day, {s.label}</Text>
        <View style={styles.table}>
          <View style={styles.tableHead}>
            <Text style={styles.cName}>Day</Text>
            <Text style={styles.cNum}>Generated</Text>
            <Text style={styles.cNum}>Used</Text>
            <Text style={styles.cNum}>Bought</Text>
            <Text style={styles.cNum}>Sent</Text>
          </View>
          {s.daily.map((d) => (
            <View style={styles.tableRow} key={d.day} wrap={false}>
              <Text style={styles.cName}>{dayShort(d.day)}</Text>
              <Text style={styles.cNum}>{(d.pvKwh ?? 0).toFixed(1)}</Text>
              <Text style={styles.cNum}>{d.loadKwh.toFixed(1)}</Text>
              <Text style={styles.cNum}>{d.importKwh.toFixed(1)}</Text>
              <Text style={styles.cNum}>{d.exportKwh.toFixed(1)}</Text>
            </View>
          ))}
        </View>
        <Text style={styles.note}>All figures in kWh.</Text>
        <Footer s={s} />
      </Page>
    </Document>
  );
}

export async function generateStatementPdf(data: StatementData): Promise<Buffer> {
  return renderToBuffer(<Statement s={data} />);
}
